version: '3.8'

services:
  finance-service:
    build: .
    container_name: finance-service
    ports:
      - "8004:8004"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - NACOS_SERVER_ADDR=nacos:8848
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=finance_db
      - MYSQL_USERNAME=finance_user
      - MYSQL_PASSWORD=finance_password
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - ROCKETMQ_NAME_SERVER=rocketmq-nameserver:9876
    depends_on:
      - mysql
      - redis
      - rocketmq-nameserver
    networks:
      - cex-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8004/api/v1/finance/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  mysql:
    image: mysql:8.0
    container_name: finance-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: finance_db
      MYSQL_USER: finance_user
      MYSQL_PASSWORD: finance_password
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - cex-network
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password

  redis:
    image: redis:7-alpine
    container_name: finance-redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - cex-network
    restart: unless-stopped
    command: redis-server --appendonly yes

  rocketmq-nameserver:
    image: apache/rocketmq:4.9.4
    container_name: finance-rocketmq-nameserver
    ports:
      - "9876:9876"
    volumes:
      - rocketmq_nameserver_logs:/home/rocketmq/logs
    networks:
      - cex-network
    command: sh mqnamesrv
    restart: unless-stopped

  rocketmq-broker:
    image: apache/rocketmq:4.9.4
    container_name: finance-rocketmq-broker
    ports:
      - "10909:10909"
      - "10911:10911"
    volumes:
      - rocketmq_broker_logs:/home/rocketmq/logs
      - rocketmq_broker_store:/home/rocketmq/store
    networks:
      - cex-network
    depends_on:
      - rocketmq-nameserver
    environment:
      NAMESRV_ADDR: rocketmq-nameserver:9876
    command: sh mqbroker -n rocketmq-nameserver:9876 -c /home/rocketmq/conf/broker.conf
    restart: unless-stopped

volumes:
  mysql_data:
  redis_data:
  rocketmq_nameserver_logs:
  rocketmq_broker_logs:
  rocketmq_broker_store:

networks:
  cex-network:
    driver: bridge