# =================================================================
# Sentinel Configuration
# Service: finance-service
# Group: finance-service
# Environment: All
# =================================================================

spring:
  cloud:
    sentinel:
      # Transport configuration
      transport:
        dashboard: sentinel:8080
        port: 8719
        client-ip: ${spring.cloud.client.ip-address}
      eager: true

      # Datasource configuration
      datasource:
        # Flow control rules
        flow-rules:
          nacos:
            server-addr: nacos:8848
            dataId: sentinel-finance-service-flow-rules.json
            rule-type: flow
            data-type: json

        # Degrade rules
        degrade-rules:
          nacos:
            server-addr: nacos:8848
            dataId: sentinel-finance-service-degrade-rules.json
            rule-type: degrade
            data-type: json

        # System rules
        system-rules:
          nacos:
            server-addr: nacos:8848
            dataId: sentinel-finance-service-system-rules.json
            rule-type: system
            data-type: json

        # Authority rules
        authority-rules:
          nacos:
            server-addr: nacos:8848
            dataId: sentinel-finance-service-authority-rules.json
            rule-type: authority
            data-type: json

      # Filter configuration
      filter:
        enabled: true
        order: -2147483648

      # Log configuration
      log:
        dir: logs/csp/
        switch-pid: false

      # Metric configuration
      metric:
        charset: UTF-8
        single-file-size: 52428800
        total-file-count: 6

# Flow control rules
sentinel:
  flow:
    # Financial report flow control
    finance-report:
      resource: finance-report
      count: 500
      grade: 1
      strategy: 0
      controlBehavior: 0
      clusterMode: false
      warmUpPeriodSec: 10
      maxQueueingTimeMs: 500

    # Asset statistics API flow control
    finance-api-asset-stats:
      resource: finance-api-asset-stats
      count: 300
      grade: 1
      strategy: 0
      controlBehavior: 0
      clusterMode: false
      warmUpPeriodSec: 5
      maxQueueingTimeMs: 200

    # Transaction statistics API flow control
    finance-api-transaction-stats:
      resource: finance-api-transaction-stats
      count: 300
      grade: 1
      strategy: 0
      controlBehavior: 0
      clusterMode: false
      warmUpPeriodSec: 5
      maxQueueingTimeMs: 200

    # Revenue analysis API flow control
    finance-api-revenue:
      resource: finance-api-revenue
      count: 200
      grade: 1
      strategy: 0
      controlBehavior: 0
      clusterMode: false
      warmUpPeriodSec: 10
      maxQueueingTimeMs: 300

    # Risk control API flow control
    finance-api-risk:
      resource: finance-api-risk
      count: 100
      grade: 1
      strategy: 0
      controlBehavior: 0
      clusterMode: false
      warmUpPeriodSec: 15
      maxQueueingTimeMs: 400

  # Degrade rules
  degrade:
    finance-report:
      resource: finance-report
      grade: 0
      count: 5
      timeWindow: 60
      minRequestAmount: 10
      slowRatioThreshold: 0.5
      statIntervalMs: 1000

    finance-api-revenue:
      resource: finance-api-revenue
      grade: 0
      count: 3
      timeWindow: 30
      minRequestAmount: 5
      slowRatioThreshold: 0.5
      statIntervalMs: 1000

  # System protection rules
  system:
    highestCpuUsage: 0.8
    highestSystemLoad: 8.0
    qps: 2000
    avgRt: 2000
    maxThread: 200

# Health check configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,sentinel
  endpoint:
    health:
      show-details: always