# =================================================================
# 通用配置 - Common Configuration (Nacos版本)
# 服务名称: wallet-service
# 配置组: wallet-service
# 适用于: 所有环境的基础配置
# =================================================================

# 基础应用配置
spring:
  application:
    name: wallet-service

  # Spring Cloud 配置
  cloud:
    # Sentinel 流量控制配置
    sentinel:
      transport:
        dashboard: localhost:8858
        port: 8719
      eager: true
      datasource:
        flow-rules:
          nacos:
            server-addr: localhost:8848
            dataId: sentinel-wallet-service-flow-rules.json
            rule-type: flow
            data-type: json
        degrade-rules:
          nacos:
            server-addr: localhost:8848
            dataId: sentinel-wallet-service-degrade-rules.json
            rule-type: degrade
            data-type: json

# 业务配置
cex:
  # JWT 配置
  jwt:
    enabled: true
    secret: your-jwt-secret-key-at-least-32-bytes-long-for-security
    expiration: 86400000  # 24小时过期时间
    refresh-expiration: 604800000  # 7天刷新token过期时间
    issuer: PPCEX

  # 钱包服务配置
  wallet:
    # 钱包基础配置
    basic:
      hot-wallet-min-balance: 0.1
      hot-wallet-max-balance: 10000
      withdraw-audit-amount: 10
      auto-withdraw-enabled: true

    # 充值配置
    recharge:
      auto-confirm-enabled: true
      min-confirmations: 6
      check-interval: 60000

    # 提现配置
    withdraw:
      daily-limit: 100000
      fee-amount: 0.001
      auto-audit-enabled: false
      max-retry-times: 3

    # 监控配置
    monitor:
      balance-threshold: 0.1
      check-interval: 300000
      transaction-confirm-interval: 60000

    # 支持的数字货币
    supported-currencies:
      - BTC
      - ETH
      - USDT
      - TRX
      - USDC

    # 链配置
    chains:
      bitcoin:
        enabled: true
        min-confirmations: 6
        fee-amount: 0.0001
      ethereum:
        enabled: true
        min-confirmations: 12
        gas-limit: 21000
        gas-price: 20000000000
      tron:
        enabled: true
        min-confirmations: 19
        fee-limit: 1000000

# 加密配置
crypto:
  aes:
    key: default-aes-key-32-characters-long
  rsa:
    private-key: default-rsa-private-key
    public-key: default-rsa-public-key

# 区块链配置
blockchain:
  ethereum:
    rpc-url: https://mainnet.infura.io/v3/YOUR_PROJECT_ID
    chain-id: 1
    gas-limit: 21000
    gas-price: 20000000000
  tron:
    rpc-url: https://api.trongrid.io
    chain-id: 1
    fee-limit: 1000000

# MyBatis Plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath:mapper/*.xml

# 安全配置
security:
  # 允许匿名访问的路径
  permit-all:
    - /wallet/api/v1/public/**
    - /wallet/doc.html
    - /wallet/swagger-ui/**
    - /wallet/v3/api-docs/**
    - /wallet/actuator/**
    - /wallet/favicon.ico
    - /wallet/error

  # 跨域配置
  cors:
    allowed-origins: ["*"]
    allowed-methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    allowed-headers: ["*"]
    exposed-headers: ["Authorization", "Content-Disposition"]
    allow-credentials: true
    max-age: 3600

  # 请求限流配置
  rate-limit:
    enabled: true
    global-limit: 1000  # 全局限流（请求/分钟）
    api-limits:
      "/wallet/api/v1/wallet/balance": 500    # 余额查询接口限流
      "/wallet/api/v1/wallet/withdraw": 50    # 提现接口限流
      "/wallet/api/v1/wallet/deposit": 100     # 充值接口限流
      "/wallet/api/v1/wallet/transfer": 100    # 转账接口限流

# 监控配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,env,beans
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
    metrics:
      enabled: true
      export:
        prometheus:
          enabled: true
    info:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
      profile: ${spring.profiles.active}
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5, 0.95, 0.99
    web:
      server:
        request:
          autotime:
            enabled: true

# 日志配置
logging:
  level:
    root: INFO
    com.ppcex.wallet: INFO
    com.ppcex.common: INFO
    org.springframework.web: DEBUG
    org.springframework.cloud: WARN
    com.alibaba.nacos.client: WARN
    io.lettuce.core: WARN
    com.zaxxer.hikari: WARN
    org.apache.rocketmq: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] [%X{traceId}] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] [%X{traceId}] %-5level %logger{36} - %msg%n"
  file:
    name: logs/wallet-service.log
    max-size: 100MB
    max-history: 30
    total-size-cap: 1GB
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 30
      total-size-cap: 1GB
      clean-history-on-start: false

# 线程池配置
thread-pool:
  core:
    core-size: 10
    max-size: 50
    queue-capacity: 1000
    keep-alive-seconds: 60
    thread-name-prefix: wallet-service-core-
  async:
    core-size: 5
    max-size: 20
    queue-capacity: 500
    keep-alive-seconds: 60
    thread-name-prefix: wallet-service-async-

# 缓存配置
cache:
  # 本地缓存配置
  local:
    enabled: true
    maximum-size: 2000
    expire-after-write: 300  # 5分钟
    expire-after-access: 600  # 10分钟

  # Redis缓存配置
  redis:
    enabled: true
    default-expiration: 3600  # 1小时
    key-prefix: "wallet:"
    use-key-prefix: true
    cache-null-values: false
    time-to-live: 3600000

  # 缓存名称配置
  caches:
    wallet-balance:
      ttl: 60    # 1分钟
      maximum-size: 5000
    transaction-history:
      ttl: 300   # 5分钟
      maximum-size: 1000
    address-info:
      ttl: 3600  # 1小时
      maximum-size: 2000

# 环境特定配置注释
# =================================================================
# 不同环境需要覆盖的配置示例：
#
# 开发环境 (common-config-dev.yaml):
# - spring.cloud.sentinel.transport.dashboard: dev-sentinel:8858
# - logging.level.com.ppcex.wallet: DEBUG
#
# 测试环境 (common-config-test.yaml):
# - spring.cloud.sentinel.transport.dashboard: test-sentinel:8858
# - logging.level.com.ppcex.wallet: INFO
#
# 生产环境 (common-config-prod.yaml):
# - spring.cloud.sentinel.transport.dashboard: prod-sentinel-cluster:8858
# - logging.level.com.ppcex.wallet: WARN
# - cex.wallet.jwt.secret: 通过环境变量注入
# =================================================================