# =================================================================
# Redis Configuration
# Service: wallet-service
# Group: wallet-service
# Environment: All
# =================================================================

spring:
  data:
    redis:
      # Connection configuration
      host: localhost
      port: 6379
      password: "redis123456"
      database: 0
      username: "cex_user"

      # Connection pool configuration
      lettuce:
        pool:
          max-active: 50
          max-wait: 10000ms
          max-idle: 20
          min-idle: 5
          time-between-eviction-runs: 30000ms

      # Timeout configuration
      timeout: 10000ms
      connect-timeout: 10000ms
      read-timeout: 10000ms

      # Client name
      client-name: wallet-service-redis-client

      # Serialization configuration
      serialization:
        key-serializer: org.springframework.data.redis.serializer.StringRedisSerializer
        value-serializer: org.springframework.data.redis.serializer.GenericJackson2JsonRedisSerializer

  # Spring Cache configuration
  cache:
    type: redis
    redis:
      time-to-live: 3600000
      cache-null-values: false
      key-prefix: "wallet:"
      use-key-prefix: true

# Business cache configuration
cache:
  config:
    # Wallet balance cache
    wallet-balance:
      ttl: 60
      max-size: 5000
      key-prefix: "wallet:balance:"

    # Transaction history cache
    transaction-history:
      ttl: 300
      max-size: 1000
      key-prefix: "wallet:history:"

    # Address info cache
    address-info:
      ttl: 3600
      max-size: 2000
      key-prefix: "wallet:address:"

    # Hot wallet balance cache
    hot-wallet-balance:
      ttl: 30
      max-size: 1000
      key-prefix: "wallet:hot:"

    # Cold wallet balance cache
    cold-wallet-balance:
      ttl: 300
      max-size: 100
      key-prefix: "wallet:cold:"

    # Withdrawal cache
    withdrawal-cache:
      ttl: 1800
      max-size: 5000
      key-prefix: "wallet:withdraw:"

    # Deposit cache
    deposit-cache:
      ttl: 600
      max-size: 5000
      key-prefix: "wallet:deposit:"

# Redis pub/sub configuration
redis-pubsub:
  enabled: true
  channels:
    wallet-updates: "wallet:updates"
    transaction-events: "wallet:transaction:events"
    balance-changes: "wallet:balance:changes"
    withdrawal-requests: "wallet:withdrawal:requests"
    deposit-confirmations: "wallet:deposit:confirmations"

# Redis distributed lock configuration
redis-lock:
  enabled: true
  key-prefix: "wallet:lock:"
  lease-time: 30000  # 锁租约时间（毫秒）
  wait-time: 10000    # 等待锁时间（毫秒）
  retry-interval: 100 # 重试间隔（毫秒）

# Redis health check configuration
management:
  health:
    redis:
      enabled: true

# Redis monitoring configuration
redis-monitor:
  enabled: true
  interval: 60  # 监控间隔（秒）
  metrics:
    - used_memory
    - used_memory_peak
    - connected_clients
    - total_commands_processed
    - instantaneous_ops_per_sec
    - keyspace_hits
    - keyspace_misses
    - expired_keys
    - evicted_keys

# Redis cluster configuration (for production)
redis-cluster:
  enabled: false
  nodes:
    - host: redis-cluster-1
      port: 6379
    - host: redis-cluster-2
      port: 6379
    - host: redis-cluster-3
      port: 6379
  max-redirects: 3

# Redis sentinel configuration (for high availability)
redis-sentinel:
  enabled: false
  master: mymaster
  nodes:
    - host: redis-sentinel-1
      port: 26379
    - host: redis-sentinel-2
      port: 26379
    - host: redis-sentinel-3
      port: 26379
  database: 0

# 环境特定配置注释
# =================================================================
# 不同环境需要覆盖的配置示例：
#
# 开发环境 (redis-config-dev.yaml):
# - spring.data.redis.host: dev-redis
# - spring.data.redis.database: 0
#
# 测试环境 (redis-config-test.yaml):
# - spring.data.redis.host: test-redis-cluster
# - redis-cluster.enabled: true
#
# 生产环境 (redis-config-prod.yaml):
# - spring.data.redis.host: prod-redis-cluster
# - redis-cluster.enabled: true
# - redis-monitor.enabled: true
# =================================================================