# =================================================================
# Sentinel Configuration
# Service: wallet-service
# Group: wallet-service
# Environment: All
# =================================================================

spring:
  cloud:
    sentinel:
      # Transport configuration
      transport:
        dashboard: localhost:8858
        port: 8719
        client-ip: ${spring.cloud.client.ip-address}
      eager: true

      # Datasource configuration
      datasource:
        # Flow control rules
        flow-rules:
          nacos:
            server-addr: localhost:8848
            dataId: sentinel-wallet-service-flow-rules.json
            rule-type: flow
            data-type: json

        # Degrade rules
        degrade-rules:
          nacos:
            server-addr: localhost:8848
            dataId: sentinel-wallet-service-degrade-rules.json
            rule-type: degrade
            data-type: json

        # System rules
        system-rules:
          nacos:
            server-addr: localhost:8848
            dataId: sentinel-wallet-service-system-rules.json
            rule-type: system
            data-type: json

        # Authority rules
        authority-rules:
          nacos:
            server-addr: localhost:8848
            dataId: sentinel-wallet-service-authority-rules.json
            rule-type: authority
            data-type: json

      # Filter configuration
      filter:
        enabled: true
        order: -2147483648

      # Log configuration
      log:
        dir: logs/csp/
        switch-pid: false

      # Metric configuration
      metric:
        charset: UTF-8
        single-file-size: 52428800
        total-file-count: 6

# Flow control rules
sentinel:
  flow:
    # Wallet operation flow control
    wallet-operation:
      resource: wallet-operation
      count: 1000
      grade: 1
      strategy: 0
      controlBehavior: 0
      clusterMode: false
      warmUpPeriodSec: 10
      maxQueueingTimeMs: 500

    # Deposit API flow control
    wallet-api-deposit:
      resource: wallet-api-deposit
      count: 500
      grade: 1
      strategy: 0
      controlBehavior: 0
      clusterMode: false
      warmUpPeriodSec: 5
      maxQueueingTimeMs: 200

    # Withdrawal API flow control
    wallet-api-withdrawal:
      resource: wallet-api-withdrawal
      count: 200
      grade: 1
      strategy: 0
      controlBehavior: 0
      clusterMode: false
      warmUpPeriodSec: 10
      maxQueueingTimeMs: 300

    # Balance query API flow control
    wallet-api-balance:
      resource: wallet-api-balance
      count: 2000
      grade: 1
      strategy: 0
      controlBehavior: 0
      clusterMode: false
      warmUpPeriodSec: 3
      maxQueueingTimeMs: 100

    # Transaction history API flow control
    wallet-api-transaction:
      resource: wallet-api-transaction
      count: 1000
      grade: 1
      strategy: 0
      controlBehavior: 0
      clusterMode: false
      warmUpPeriodSec: 5
      maxQueueingTimeMs: 200

  # Degrade rules
  degrade:
    wallet-operation:
      resource: wallet-operation
      grade: 0
      count: 10
      timeWindow: 60
      minRequestAmount: 20
      slowRatioThreshold: 0.5
      statIntervalMs: 1000

    wallet-api-withdrawal:
      resource: wallet-api-withdrawal
      grade: 0
      count: 5
      timeWindow: 30
      minRequestAmount: 10
      slowRatioThreshold: 0.5
      statIntervalMs: 1000

  # System protection rules
  system:
    highestCpuUsage: 0.8
    highestSystemLoad: 10.0
    qps: 5000
    avgRt: 1000
    maxThread: 500

# Health check configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,sentinel
  endpoint:
    health:
      show-details: always