spring:
  application:
    name: user-service
  profiles:
    active: test
  main:
    allow-bean-definition-overriding: true

  config:
    import:
      - nacos:mysql-config.yaml?group=user-service&namespace=d8a0e588-e615-448b-994c-0ad931c56808&refresh=true
      - nacos:redis-config.yaml?group=user-service&namespace=d8a0e588-e615-448b-994c-0ad931c56808&refresh=true
      - nacos:common-config.yaml?group=user-service&namespace=d8a0e588-e615-448b-994c-0ad931c56808&refresh=true

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: d8a0e588-e615-448b-994c-0ad931c56808
        group: user-service
        metadata:
          version: 1.0.0
          context-path: /user
      config:
        server-addr: localhost:8848
        namespace: d8a0e588-e615-448b-994c-0ad931c56808
        group: user-service
        file-extension: yaml
        shared-configs:
          - data-id: common-config.yaml
            group: user-service
            refresh: true
          - data-id: redis-config.yaml
            group: user-service
            refresh: true
          - data-id: mysql-config.yaml
            group: user-service
            refresh: true
          - data-id: rocketmq-config.yaml
            group: user-service
            refresh: true

server:
  port: 8001
  servlet:
    context-path: /user