spring:
  application:
    name: user-service
  profiles:
    active: test
  main:
    allow-bean-definition-overriding: true

  config:
    import:
      - optional:nacos:user-common-config.yaml
      - optional:nacos:user-mysql-config.yaml
      - optional:nacos:user-redis-config.yaml
      - optional:nacos:user-rocketmq-config.yaml

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        metadata:
          version: 1.0.0
          context-path: /user
      config:
        enabled: true
        server-addr: localhost:8848
        file-extension: yaml

server:
  port: 8001
  servlet:
    context-path: /user

# Knife4j Configuration
knife4j:
  enable: true
  setting:
    language: zh_cn
    enableSwaggerModels: true
    enableDocumentManage: true
    swaggerModelName: 实体类列表
    enableVersion: false
    enableReloadCacheParameter: false
    enableFilterMultipartApis: false
    enableFilterMultipartMethods: false
    enableRequestCache: true
    enableHost: false
    enableHomeCustom: true
    homeCustomLocation: classpath:markdown/home.md
    enableAfterScript: true
    enableSwaggerAuth: true  # 启用Swagger认证
  enableRequestCache: true
  enableHost: false
  openapi:
    title: PPCEX User Service API
    description: 用户服务API文档
    email: support@ppcex.com
    concat: PPCEX Team
    url: https://www.ppcex.com
    version: v1.0.0
    license: MIT License
    license-url: https://opensource.org/licenses/MIT