spring:
  application:
    name: user-service
  profiles:
    active: test
  main:
    allow-bean-definition-overriding: true

  config:
    import:
      - optional:nacos:mysql-config.yaml?group=user-service&namespace=d8a0e588-e615-448b-994c-0ad931c56808&refresh=true
      # - optional:nacos:redis-config.yaml?group=user-service&namespace=d8a0e588-e615-448b-994c-0ad931c56808&refresh=true
      - optional:nacos:common-config.yaml?group=user-service&namespace=d8a0e588-e615-448b-994c-0ad931c56808&refresh=true
      - optional:nacos:rocketmq-config.yaml?group=user-service&namespace=d8a0e588-e615-448b-994c-0ad931c56808&refresh=true

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: d8a0e588-e615-448b-994c-0ad931c56808
        group: user-service
        metadata:
          version: 1.0.0
          context-path: /user
      config:
        server-addr: localhost:8848
        namespace: d8a0e588-e615-448b-994c-0ad931c56808
        group: user-service
        file-extension: yaml

server:
  port: 8002
  servlet:
    context-path: /user