version: '3.8'

services:
  # Database
  mysql-master:
    image: mysql:8.0
    container_name: mysql-master
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: cex_db
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_REPLICATION_USER: ${MYSQL_REPLICATION_USER}
      MYSQL_REPLICATION_PASSWORD: ${MYSQL_REPLICATION_PASSWORD}
    volumes:
      - mysql-master-data:/var/lib/mysql
      - ./scripts/mysql/master.cnf:/etc/mysql/conf.d/master.cnf
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - cex-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
        reservations:
          cpus: '1.0'
          memory: 2G

  mysql-slave:
    image: mysql:8.0
    container_name: mysql-slave
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: cex_db
      MYSQL_MASTER_HOST: mysql-master
      MYSQL_REPLICATION_USER: ${MYSQL_REPLICATION_USER}
      MYSQL_REPLICATION_PASSWORD: ${MYSQL_REPLICATION_PASSWORD}
    volumes:
      - mysql-slave-data:/var/lib/mysql
      - ./scripts/mysql/slave.cnf:/etc/mysql/conf.d/slave.cnf
    ports:
      - "3307:3306"
    networks:
      - cex-network
    depends_on:
      mysql-master:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 1G

  # Redis Cluster
  redis-1:
    image: redis:7-alpine
    container_name: redis-1
    command: redis-server --port 6379 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes --protected-mode no
    volumes:
      - redis-1-data:/data
    ports:
      - "6379:6379"
    networks:
      - cex-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 5s
      retries: 5

  redis-2:
    image: redis:7-alpine
    container_name: redis-2
    command: redis-server --port 6380 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes --protected-mode no
    volumes:
      - redis-2-data:/data
    ports:
      - "6380:6380"
    networks:
      - cex-network
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "6380", "ping"]
      timeout: 5s
      retries: 5

  redis-3:
    image: redis:7-alpine
    container_name: redis-3
    command: redis-server --port 6381 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes --protected-mode no
    volumes:
      - redis-3-data:/data
    ports:
      - "6381:6381"
    networks:
      - cex-network
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "6381", "ping"]
      timeout: 5s
      retries: 5

  # RocketMQ
  rocketmq-nameserver:
    image: apache/rocketmq:4.9.4
    container_name: rocketmq-nameserver
    ports:
      - "9876:9876"
    volumes:
      - rocketmq-nameserver-logs:/home/rocketmq/logs
    networks:
      - cex-network
    command: sh mqnamesrv
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9876"]
      timeout: 10s
      retries: 5

  rocketmq-broker-a:
    image: apache/rocketmq:4.9.4
    container_name: rocketmq-broker-a
    ports:
      - "10911:10911"
      - "10909:10909"
    volumes:
      - rocketmq-broker-a-logs:/home/rocketmq/logs
      - rocketmq-broker-a-store:/home/rocketmq/store
      - ./scripts/rocketmq/broker-a.conf:/home/rocketmq/conf/broker.conf
    networks:
      - cex-network
    depends_on:
      rocketmq-nameserver:
        condition: service_healthy
    command: sh mqbroker -c /home/rocketmq/conf/broker.conf
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:10911"]
      timeout: 10s
      retries: 5

  rocketmq-broker-b:
    image: apache/rocketmq:4.9.4
    container_name: rocketmq-broker-b
    ports:
      - "10921:10921"
      - "10919:10919"
    volumes:
      - rocketmq-broker-b-logs:/home/rocketmq/logs
      - rocketmq-broker-b-store:/home/rocketmq/store
      - ./scripts/rocketmq/broker-b.conf:/home/rocketmq/conf/broker.conf
    networks:
      - cex-network
    depends_on:
      rocketmq-nameserver:
        condition: service_healthy
    command: sh mqbroker -c /home/rocketmq/conf/broker.conf
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:10921"]
      timeout: 10s
      retries: 5

  # Nacos
  nacos-1:
    image: nacos/nacos-server:v2.2.3
    container_name: nacos-1
    environment:
      MODE: cluster
      SPRING_DATASOURCE_PLATFORM: mysql
      MYSQL_SERVICE_HOST: mysql-master
      MYSQL_SERVICE_PORT: 3306
      MYSQL_SERVICE_DB_NAME: nacos
      MYSQL_SERVICE_USER: ${MYSQL_USER}
      MYSQL_SERVICE_PASSWORD: ${MYSQL_PASSWORD}
      NACOS_SERVERS: "nacos-1:8848 nacos-2:8848 nacos-3:8848"
      NACOS_SERVER_PORT: 8848
      PREFER_HOST_MODE: hostname
    volumes:
      - nacos-1-logs:/home/nacos/logs
    ports:
      - "8848:8848"
    networks:
      - cex-network
    depends_on:
      mysql-master:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8848/nacos/v1/ns/operator/switches"]
      timeout: 10s
      retries: 5

  nacos-2:
    image: nacos/nacos-server:v2.2.3
    container_name: nacos-2
    environment:
      MODE: cluster
      SPRING_DATASOURCE_PLATFORM: mysql
      MYSQL_SERVICE_HOST: mysql-master
      MYSQL_SERVICE_PORT: 3306
      MYSQL_SERVICE_DB_NAME: nacos
      MYSQL_SERVICE_USER: ${MYSQL_USER}
      MYSQL_SERVICE_PASSWORD: ${MYSQL_PASSWORD}
      NACOS_SERVERS: "nacos-1:8848 nacos-2:8848 nacos-3:8848"
      NACOS_SERVER_PORT: 8848
      PREFER_HOST_MODE: hostname
    volumes:
      - nacos-2-logs:/home/nacos/logs
    ports:
      - "8849:8848"
    networks:
      - cex-network
    depends_on:
      mysql-master:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8848/nacos/v1/ns/operator/switches"]
      timeout: 10s
      retries: 5

  nacos-3:
    image: nacos/nacos-server:v2.2.3
    container_name: nacos-3
    environment:
      MODE: cluster
      SPRING_DATASOURCE_PLATFORM: mysql
      MYSQL_SERVICE_HOST: mysql-master
      MYSQL_SERVICE_PORT: 3306
      MYSQL_SERVICE_DB_NAME: nacos
      MYSQL_SERVICE_USER: ${MYSQL_USER}
      MYSQL_SERVICE_PASSWORD: ${MYSQL_PASSWORD}
      NACOS_SERVERS: "nacos-1:8848 nacos-2:8848 nacos-3:8848"
      NACOS_SERVER_PORT: 8848
      PREFER_HOST_MODE: hostname
    volumes:
      - nacos-3-logs:/home/nacos/logs
    ports:
      - "8850:8848"
    networks:
      - cex-network
    depends_on:
      mysql-master:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8848/nacos/v1/ns/operator/switches"]
      timeout: 10s
      retries: 5

  # Application Services
  gateway-service:
    build:
      context: ./backend/gateway-service
      dockerfile: Dockerfile
    container_name: gateway-service
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      NACOS_SERVER_ADDR: nacos-1:8848,nacos-2:8848,nacos-3:8848
      NACOS_NAMESPACE: cex-prod
      NACOS_GROUP: DEFAULT_GROUP
    networks:
      - cex-network
    depends_on:
      nacos-1:
        condition: service_healthy
      nacos-2:
        condition: service_healthy
      nacos-3:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      timeout: 10s
      retries: 5
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

  user-service:
    build:
      context: ./backend/user-service
      dockerfile: Dockerfile
    container_name: user-service
    ports:
      - "8001:8001"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      NACOS_SERVER_ADDR: nacos-1:8848,nacos-2:8848,nacos-3:8848
      NACOS_NAMESPACE: cex-prod
      NACOS_GROUP: DEFAULT_GROUP
    networks:
      - cex-network
    depends_on:
      mysql-master:
        condition: service_healthy
      redis-1:
        condition: service_healthy
      rocketmq-nameserver:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/user/actuator/health"]
      timeout: 10s
      retries: 5
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

  trade-service:
    build:
      context: ./backend/trade-service
      dockerfile: Dockerfile
    container_name: trade-service
    ports:
      - "8002:8002"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      NACOS_SERVER_ADDR: nacos-1:8848,nacos-2:8848,nacos-3:8848
      NACOS_NAMESPACE: cex-prod
      NACOS_GROUP: DEFAULT_GROUP
    networks:
      - cex-network
    depends_on:
      mysql-master:
        condition: service_healthy
      redis-1:
        condition: service_healthy
      rocketmq-nameserver:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/trade/actuator/health"]
      timeout: 10s
      retries: 5
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          cpus: '1.0'
          memory: 1G

  wallet-service:
    build:
      context: ./backend/wallet-service
      dockerfile: Dockerfile
    container_name: wallet-service
    ports:
      - "8003:8003"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      NACOS_SERVER_ADDR: nacos-1:8848,nacos-2:8848,nacos-3:8848
      NACOS_NAMESPACE: cex-prod
      NACOS_GROUP: DEFAULT_GROUP
    networks:
      - cex-network
    depends_on:
      mysql-master:
        condition: service_healthy
      redis-1:
        condition: service_healthy
      rocketmq-nameserver:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8003/wallet/actuator/health"]
      timeout: 10s
      retries: 5
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

  market-service:
    build:
      context: ./backend/market-service
      dockerfile: Dockerfile
    container_name: market-service
    ports:
      - "8004:8004"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      NACOS_SERVER_ADDR: nacos-1:8848,nacos-2:8848,nacos-3:8848
      NACOS_NAMESPACE: cex-prod
      NACOS_GROUP: DEFAULT_GROUP
    networks:
      - cex-network
    depends_on:
      mysql-master:
        condition: service_healthy
      redis-1:
        condition: service_healthy
      rocketmq-nameserver:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8004/market/actuator/health"]
      timeout: 10s
      retries: 5
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

  match-service:
    build:
      context: ./backend/match-service
      dockerfile: Dockerfile
    container_name: match-service
    ports:
      - "8005:8005"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      NACOS_SERVER_ADDR: nacos-1:8848,nacos-2:8848,nacos-3:8848
      NACOS_NAMESPACE: cex-prod
      NACOS_GROUP: DEFAULT_GROUP
    networks:
      - cex-network
    depends_on:
      mysql-master:
        condition: service_healthy
      redis-1:
        condition: service_healthy
      rocketmq-nameserver:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8005/match/actuator/health"]
      timeout: 10s
      retries: 5
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '4.0'
          memory: 4G
        reservations:
          cpus: '2.0'
          memory: 2G

  finance-service:
    build:
      context: ./backend/finance-service
      dockerfile: Dockerfile
    container_name: finance-service
    ports:
      - "8006:8006"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      NACOS_SERVER_ADDR: nacos-1:8848,nacos-2:8848,nacos-3:8848
      NACOS_NAMESPACE: cex-prod
      NACOS_GROUP: DEFAULT_GROUP
    networks:
      - cex-network
    depends_on:
      mysql-master:
        condition: service_healthy
      redis-1:
        condition: service_healthy
      rocketmq-nameserver:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8006/finance/actuator/health"]
      timeout: 10s
      retries: 5
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

  risk-service:
    build:
      context: ./backend/risk-service
      dockerfile: Dockerfile
    container_name: risk-service
    ports:
      - "8007:8007"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      NACOS_SERVER_ADDR: nacos-1:8848,nacos-2:8848,nacos-3:8848
      NACOS_NAMESPACE: cex-prod
      NACOS_GROUP: DEFAULT_GROUP
    networks:
      - cex-network
    depends_on:
      mysql-master:
        condition: service_healthy
      redis-1:
        condition: service_healthy
      rocketmq-nameserver:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8007/risk/actuator/health"]
      timeout: 10s
      retries: 5
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

  notify-service:
    build:
      context: ./backend/notify-service
      dockerfile: Dockerfile
    container_name: notify-service
    ports:
      - "8008:8008"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      NACOS_SERVER_ADDR: nacos-1:8848,nacos-2:8848,nacos-3:8848
      NACOS_NAMESPACE: cex-prod
      NACOS_GROUP: DEFAULT_GROUP
    networks:
      - cex-network
    depends_on:
      mysql-master:
        condition: service_healthy
      redis-1:
        condition: service_healthy
      rocketmq-nameserver:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8008/notify/actuator/health"]
      timeout: 10s
      retries: 5
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      NEXT_PUBLIC_WS_URL: ${NEXT_PUBLIC_WS_URL}
      NEXT_PUBLIC_CHAIN_ID: ${NEXT_PUBLIC_CHAIN_ID}
      NEXT_PUBLIC_NETWORK_ID: ${NEXT_PUBLIC_NETWORK_ID}
    networks:
      - cex-network
    depends_on:
      gateway-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      timeout: 10s
      retries: 5
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M

  # Monitoring
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    networks:
      - cex-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9090/-/healthy"]
      timeout: 10s
      retries: 5

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD}
    volumes:
      - grafana-data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources
    networks:
      - cex-network
    depends_on:
      prometheus:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      timeout: 10s
      retries: 5

  # Load Balancer
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    networks:
      - cex-network
    depends_on:
      - frontend
      - gateway-service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      timeout: 10s
      retries: 5

volumes:
  mysql-master-data:
  mysql-slave-data:
  redis-1-data:
  redis-2-data:
  redis-3-data:
  rocketmq-nameserver-logs:
  rocketmq-broker-a-logs:
  rocketmq-broker-a-store:
  rocketmq-broker-b-logs:
  rocketmq-broker-b-store:
  nacos-1-logs:
  nacos-2-logs:
  nacos-3-logs:
  prometheus-data:
  grafana-data:

networks:
  cex-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16