spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/wallet_db?useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-test-query: SELECT 1

  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    database: 0
    timeout: 10000
    lettuce:
      pool:
        max-active: 50
        max-idle: 20
        min-idle: 5
        max-wait: 10000

  # RocketMQ配置
  rocketmq:
    name-server: ${ROCKETMQ_NAMESRV:localhost:9876}
    producer:
      group: wallet-producer
      send-message-timeout: 3000
      retry-times-when-send-failed: 3
      retry-times-when-send-async-failed: 3
    consumer:
      listeners:
        wallet-consumer:
          group: wallet-consumer
          topic: wallet-topic
          selector-expression: "WALLET_RECHARGE || WALLET_WITHDRAW || WALLET_TRANSFER"
          consume-thread-min: 20
          consume-thread-max: 64
          pull-batch-size: 32
        asset-consumer:
          group: asset-consumer
          topic: asset-topic
          selector-expression: "ASSET_CHANGE"
          consume-thread-min: 20
          consume-thread-max: 64
          consume-mode: ORDERLY

# MyBatis Plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath:mapper/*.xml

# 加密配置
crypto:
  aes:
    key: ${AES_KEY:default-aes-key-32-characters-long}
  rsa:
    private-key: ${RSA_PRIVATE_KEY:default-rsa-private-key}
    public-key: ${RSA_PUBLIC_KEY:default-rsa-public-key}

# 区块链配置
blockchain:
  ethereum:
    rpc-url: ${ETH_RPC_URL:https://mainnet.infura.io/v3/YOUR_PROJECT_ID}
    chain-id: 1
    gas-limit: 21000
    gas-price: 20000000000
  tron:
    rpc-url: ${TRON_RPC_URL:https://api.trongrid.io}
    chain-id: 1
    fee-limit: 1000000

# 监控配置
monitor:
  wallet:
    balance-threshold: 0.1
    check-interval: 300000
  transaction:
    confirm-check-interval: 60000
    max-retry-times: 3

# 业务配置
business:
  wallet:
    hot-wallet-min-balance: 0.1
    hot-wallet-max-balance: 10000
    withdraw-audit-amount: 10
    auto-withdraw-enabled: true
  recharge:
    auto-confirm-enabled: true
    min-confirmations: 6
  withdraw:
    daily-limit: 100000
    fee-amount: 0.001
    auto-audit-enabled: false