spring:
  application:
    name: wallet-service
  profiles:
    active: test
  main:
    allow-bean-definition-overriding: true
    lazy-initialization: false
    banner-mode: "off"

  config:
    import:
      - optional:nacos:wallet-common-config.yaml
      - optional:nacos:wallet-mysql-config.yaml
      - optional:nacos:wallet-redis-config.yaml
      - optional:nacos:wallet-rocketmq-config.yaml

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        metadata:
          version: 1.0.0
          context-path: /wallet
      config:
        enabled: true
        server-addr: localhost:8848
        file-extension: yaml
    sentinel:
      transport:
        dashboard: sentinel:8080
        port: 8719
      eager: true
      datasource:
        flow-rules:
          nacos:
            server-addr: nacos:8848
            dataId: sentinel-wallet-service-flow-rules.json
            rule-type: flow
            data-type: json
        degrade-rules:
          nacos:
            server-addr: nacos:8848
            dataId: sentinel-wallet-service-degrade-rules.json
            rule-type: degrade
            data-type: json

server:
  port: 8004
  servlet:
    context-path: /wallet

# Knife4j Configuration
knife4j:
  enable: true
  setting:
    language: zh_cn
    enableSwaggerModels: true
    enableDocumentManage: true
    swaggerModelName: 实体类列表
    enableVersion: false
    enableReloadCacheParameter: false
    enableFilterMultipartApis: false
    enableFilterMultipartMethods: false
    enableRequestCache: true
    enableHost: false
    enableHomeCustom: true
    homeCustomLocation: classpath:markdown/home.md
    enableAfterScript: true
    enableSwaggerAuth: true  # 启用Swagger认证
  enableRequestCache: true
  enableHost: false
  openapi:
    title: PPCEX Wallet Service API
    description: 钱包服务API文档
    email: support@ppcex.com
    concat: PPCEX Team
    url: https://www.ppcex.com
    version: v1.0.0
    license: MIT License
    license-url: https://opensource.org/licenses/MIT

debug: false