server:
  port: 9000
  servlet:
    context-path: /

spring:
  application:
    name: gateway-service
  profiles:
    active: test
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
    banner-mode: "off"
    lazy-initialization: false

  config:
    import:
      - optional:nacos:gateway-common-config.yaml
      - optional:nacos:gateway-redis-config.yaml
      - optional:nacos:gateway-gateway-config.yaml
      - optional:nacos:gateway-knife4j-config.yaml

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        metadata:
          version: 1.0.0
          context-path: /
      config:
        enabled: true
        server-addr: localhost:8848
        file-extension: yaml

debug: false

# 网关健康检查配置
gateway:
  health:
    check:
      interval: 60  # 健康检查间隔，单位秒（默认60秒）
      timeout: 10   # 健康检查超时时间，单位秒（默认10秒）