spring:
  application:
    name: market-service
  profiles:
    active: test
  main:
    allow-bean-definition-overriding: true
    lazy-initialization: false
    banner-mode: "off"

  config:
    import:
      - optional:nacos:market-common-config.yaml
      - optional:nacos:market-mysql-config.yaml
      - optional:nacos:market-redis-config.yaml
      - optional:nacos:market-rocketmq-config.yaml

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        metadata:
          version: 1.0.0
          context-path: /market
      config:
        enabled: true
        server-addr: localhost:8848
        file-extension: yaml
    stream:
      function:
        definition: marketTopic;tickTopic
      rocketmq:
        binder:
          name-server: localhost:9876

server:
  port: 8006
  servlet:
    context-path: /market

# Knife4j Configuration
knife4j:
  enable: true
  setting:
    language: zh_cn
    enableSwaggerModels: true
    enableDocumentManage: true
    swaggerModelName: 实体类列表
    enableVersion: false
    enableReloadCacheParameter: false
    enableFilterMultipartApis: false
    enableFilterMultipartMethods: false
    enableRequestCache: true
    enableHost: false
    enableHomeCustom: true
    homeCustomLocation: classpath:markdown/home.md
    enableAfterScript: true
    enableSwaggerAuth: true
  enableRequestCache: true
  enableHost: false
  openapi:
    title: PPCEX Market Service API
    description: 行情服务API文档
    email: support@ppcex.com
    concat: PPCEX Team
    url: https://www.ppcex.com
    version: v1.0.0
    license: MIT License
    license-url: https://opensource.org/licenses/MIT

# WebSocket Configuration
websocket:
  enabled: true
  path: /ws/market
  allowed-origins: ["*"]
  message-size-limit: 65536
  send-time-limit: 10000
  send-buffer-size-limit: 512000

debug: false