# =================================================================
# Spring Boot 3.1.5 + Spring Cloud 2022.0.4 + Spring Cloud Alibaba 2022.0.0.0
# 服务名称: market-service
# 环境配置: test
# =================================================================

spring:
  # 应用基础配置
  application:
    name: market-service
  profiles:
    active: test
  main:
    allow-bean-definition-overriding: true
    lazy-initialization: false
    banner-mode: "off"

  # 配置中心
  config:
    import:
      - optional:nacos:market-config.yaml

  # 服务注册与发现
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: public
        group: DEFAULT_GROUP
        metadata:
          version: 1.0.0
          context-path: /market
          preserved.heart.beat.interval: 5000
          preserved.heart.beat.timeout: 15000
          preserved.ip.delete.timeout: 30000
      config:
        enabled: true
        server-addr: localhost:8848
        namespace: public
        group: DEFAULT_GROUP
        file-extension: yaml
        refresh-enabled: true
        shared-configs:
          - data-id: common-config.yaml
            group: DEFAULT_GROUP
            refresh: true

    # Sentinel 流量控制
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
        client-ip: ${spring.cloud.client.ip-address}
      eager: true
      datasource:
        flow-rules:
          nacos:
            server-addr: localhost:8848
            dataId: sentinel-market-service-flow-rules.json
            groupId: DEFAULT_GROUP
            rule-type: flow
            data-type: json
        degrade-rules:
          nacos:
            server-addr: localhost:8848
            dataId: sentinel-market-service-degrade-rules.json
            groupId: DEFAULT_GROUP
            rule-type: degrade
            data-type: json

    # Stream RocketMQ 配置
    stream:
      default-binder: rocketmq
      function:
        definition: marketTopic;tickTopic;tradeTopic
      rocketmq:
        binder:
          name-server: ${ROCKETMQ_NAMESRV:localhost:9876}
          group: market-service-group
        bindings:
          marketTopic-in-0:
            destination: market-topic
            content-type: application/json
            group: market-service-group
            consumer:
              tag: TICKER_UPDATE || TRADE_UPDATE || DEPTH_UPDATE || SYSTEM_COMMAND
          marketTopic-out-0:
            destination: market-topic
            content-type: application/json
            producer:
              sync: true
              send-timeout: 3000

  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ppcex_market?useSSL=false&serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&allowPublicKeyRetrieval=true&autoReconnect=true&failOverReadOnly=false&maxReconnects=3
    username: root
    password: root123
    hikari:
      pool-name: MarketServiceHikariCP
      connection-timeout: 30000
      validation-timeout: 5000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000
      minimum-idle: 10
      maximum-pool-size: 50
      connection-test-query: SELECT 1
      connection-init-sql: SET NAMES utf8mb4

  # Redis 配置
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:redis123456}
      database: ${REDIS_DATABASE:2}
      username: ${REDIS_USERNAME:cex_market}
      timeout: 10000ms
      connect-timeout: 10000ms
      lettuce:
        pool:
          max-active: 100
          max-wait: -1ms
          max-idle: 20
          min-idle: 5
          time-between-eviction-runs: 30000ms
      client-name: market-service-redis-client

  # 缓存配置
  cache:
    type: redis
    redis:
      time-to-live: 3600000
      cache-null-values: false
      key-prefix: "market:"
      use-key-prefix: true

  # 线程池配置
  task:
    execution:
      pool:
        core-size: 20
        max-size: 100
        queue-capacity: 2000
        keep-alive: 60s
        thread-name-prefix: market-service-task-
    scheduling:
      pool:
        size: 10
        thread-name-prefix: market-service-scheduling-

  # Flyway 配置
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    clean-disabled: true
    table: flyway_schema_history
    placeholders:
      db_name: ppcex_market

# Web服务器配置
server:
  port: 8005
  servlet:
    context-path: /market
  tomcat:
    threads:
      max: 200
      min-spare: 10
    accept-count: 100
    connection-timeout: 20000
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json

# 业务配置
cex:
  jwt:
    enabled: true
    secret: ${JWT_SECRET:your-jwt-secret-key-at-least-32-bytes-long-for-security}
    expiration: 86400000
    refresh-expiration: 604800000
    issuer: PPCEX

  market:
    # 数据同步配置
    sync:
      pairs:
        enabled: true
        sync-interval: 300
        retry-interval: 60
        max-retry: 3
      ticker:
        enabled: true
        update-interval: 1000
        batch-size: 100
        cache-ttl: 60
      kline:
        enabled: true
        intervals: ["1m", "5m", "15m", "30m", "1h", "4h", "1d", "1w", "1M"]
        history-limit: 1000
        generate-interval: 60000
      depth:
        enabled: true
        update-interval: 500
        depth-limit: 20
        snapshot-interval: 5000
      trade:
        enabled: true
        update-interval: 2000
        history-limit: 1000

    # WebSocket 配置
    websocket:
      enabled: true
      max-sessions: 10000
      session-timeout: 300000
      message-size-limit: 65536
      heartbeat-interval: 30000

# WebSocket配置（向后兼容）
websocket:
  enabled: true
  path: /ws/market
  allowed-origins: ["*"]
  message-size-limit: 65536
  send-time-limit: 10000
  send-buffer-size-limit: 512000

# 安全配置
security:
  permit-all:
    - /market/api/v1/public/**
    - /market/doc.html
    - /market/swagger-ui/**
    - /market/v3/api-docs/**
    - /market/actuator/**
    - /market/ws/**

  cors:
    allowed-origins: ["*"]
    allowed-methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    allowed-headers: ["*"]
    exposed-headers: ["Authorization", "Content-Disposition"]
    allow-credentials: true
    max-age: 3600

  rate-limit:
    enabled: true
    global-limit: 5000
    api-limits:
      "/market/api/v1/market/ticker/*": 1000
      "/market/api/v1/market/klines": 2000
      "/market/api/v1/market/trades": 1000
      "/market/api/v1/market/depth": 2000

# 监控配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,env,beans
      base-path: /actuator
      discovery:
        enabled: true
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
    info:
      enabled: true
      git:
        mode: full
  metrics:
    tags:
      application: ${spring.application.name}
      profile: ${spring.profiles.active}
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5, 0.95, 0.99

# 日志配置
logging:
  level:
    root: INFO
    com.ppcex.market: INFO
    com.ppcex.common: INFO
    org.springframework.web: DEBUG
    org.springframework.cloud: WARN
    com.alibaba.nacos.client: WARN
    io.lettuce.core: WARN
    com.zaxxer.hikari: WARN
    org.apache.rocketmq: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] [%X{traceId}] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] [%X{traceId}] %-5level %logger{36} - %msg%n"
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 30
      total-size-cap: 1GB

# MyBatis Plus 配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ppcex.market.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    lazy-loading-enabled: true
    multiple-result-sets-enabled: true
    use-column-label: true
    use-generated-keys: true
    auto-mapping-behavior: partial
    default-statement-timeout: 25000
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    local-cache-scope: statement
  global-config:
    db-config:
      id-type: auto
      table-underline: true
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      table-prefix: "market_"
    banner: false

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui/index.html

# API文档配置
knife4j:
  enable: true
  setting:
    language: zh_cn
    enableSwaggerModels: true
    enableDocumentManage: true
    swaggerModelName: 实体类列表
    enableRequestCache: true
    enableHost: false
    enableAfterScript: true
    enableSwaggerAuth: true
  info:
    title: PPCEX Market Service API
    description: 行情服务API文档
    email: support@ppcex.com
    concat: PPCEX Team
    url: https://www.ppcex.com
    version: v1.0.0
    license:
      name: MIT License
      url: https://opensource.org/licenses/MIT

debug: false