# =================================================================
# Redis配置
# Service: gateway-service
# Environment: All
# =================================================================

spring:
  # Redis配置
  data:
    redis:
      # 连接配置
      host: redis
      port: 6379
      password: "redis123456"
      database: 1
      username: "cex_user"

      # 连接池配置
      lettuce:
        pool:
          max-active: 200
          max-wait: -1ms
          max-idle: 20
          min-idle: 5
          time-between-eviction-runs: 30000ms
          min-evictable-idle-time: 60000ms
        shutdown-timeout: 100ms

      # 超时配置
      timeout: 10000ms
      connect-timeout: 10000ms
      read-timeout: 10000ms

      # 客户端名称
      client-name: gateway-service-redis-client

      # 序列化配置
      serialization:
        key-serializer: org.springframework.data.redis.serializer.StringRedisSerializer
        value-serializer: org.springframework.data.redis.serializer.GenericJackson2JsonRedisSerializer

  # Spring Cache配置
  cache:
    type: redis
    redis:
      time-to-live: 1800000  # 30分钟
      cache-null-values: false
      key-prefix: "gateway:"
      use-key-prefix: true