# Knife4j 网关聚合配置
knife4j:
  # 开启增强配置
  enable: true
  # 开启生产环境屏蔽（生产环境建议关闭）
  production: false
  # 开启Swagger文档聚合
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    doc-expansion: list
    filter: ""
    display-request-duration: true
  api-docs:
    path: /v3/api-docs
    enabled: true
  group-configs:
    - group: '网关服务'
      paths-to-match: '/api/**'
      display-name: '网关服务'
      packages-to-scan: com.ppcex.gateway.controller
  gateway:
    # 开启网关聚合
    enabled: true
    # 网关聚合策略
    strategy: discover
    # 服务发现类型
    discover:
      # 开启服务发现
      enabled: true
      # 服务发现版本（2:Spring Cloud Gateway）
      version: gateway
      # 服务名称排序方式
      service-name-sort-asc: true
      # 需要聚合的服务列表（留空表示聚合所有服务）
      include-services:
        - user-service
        - trade-service
        - wallet-service
        - finance-service
        - market-service
        - risk-service
        - notify-service
        - match-service
      # 排除的服务列表
      exclude-services:
        - gateway-service
    # 聚合文档的排序方式
    order: 1
    # 聚合文档的标签
    tags:
      - name: 网关聚合文档
        description: PPCEX网关聚合所有微服务的API文档

# 网关路由配置
spring:
  cloud:
    gateway:
      routes:
        # Knife4j 文档
        - id: knife4j-docs
          uri: forward:/doc.html
          predicates:
            - Path=/doc.html
            - Path=/doc.html/**

        # Swagger UI
        - id: swagger-ui
          uri: forward:/swagger-ui/index.html
          predicates:
            - Path=/swagger-ui
            - Path=/swagger-ui/**

        # Swagger 资源
        - id: swagger-resources
          uri: forward:/swagger-resources
          predicates:
            - Path=/swagger-resources
            - Path=/swagger-resources/**

        # v3 API 文档（聚合微服务）
        - id: v3-api-docs
          uri: forward:/v3/api-docs
          predicates:
            - Path=/v3/api-docs
            - Path=/v3/api-docs/**
        # WebJars 静态资源
        - id: webjars
          uri: forward:/webjars
          predicates:
            - Path=/webjars
            - Path=/webjars/**

# 日志配置
logging:
  level:
    com.github.xiaoymin.knife4j: DEBUG
    com.ppcex.gateway.filter: DEBUG
    org.springframework.cloud.gateway: DEBUG