# =================================================================
# 通用配置
# Service: gateway-service
# Environment: All
# =================================================================

# Nacos配置中心
spring:
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: nacos:8848
        metadata:
          version: 1.0.0
          context-path: /
      config:
        enabled: true
        server-addr: nacos:8848
        file-extension: yaml

    # 负载均衡配置
    loadbalancer:
      ribbon:
        enabled: false

    # 监控配置
    zipkin:
      base-url: http://zipkin:9411
      sender:
        type: web
    sleuth:
      sampler:
        probability: 1.0

# Sentinel配置
spring.cloud.sentinel:
  transport:
    dashboard: sentinel:8080
    port: 8719
  filter:
    enabled: true
  # 网关流控配置
  scg:
    fallback:
      mode: response
      response-body: '{"code": 429, "message": "系统繁忙，请稍后再试"}'
      response-status: 429
  datasource:
    ds1:
      nacos:
        server-addr: nacos:8848
        dataId: sentinel-gateway-service-flow-rules.json
        groupId: DEFAULT_GROUP
        rule-type: flow
    ds2:
      nacos:
        server-addr: nacos:8848
        dataId: sentinel-gateway-service-degrade-rules.json
        groupId: DEFAULT_GROUP
        rule-type: degrade

# 暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

# JWT配置
jwt:
  secret: mySecretKey123456789
  expiration: 86400000
  refresh-expiration: 604800000

# 日志配置
logging:
  level:
    root: INFO
    com.ppcex.gateway: DEBUG
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/gateway-service.log
    max-size: 100MB
    max-history: 30