# =================================================================
# 通用配置 - Common Configuration (Nacos版本)
# 服务名称: user-service
# 配置组: DEFAULT_GROUP
# 适用于: 所有环境的基础配置
# =================================================================

# 基础应用配置
spring:
  application:
    name: user-service

  # Spring Cloud 配置
  cloud:
    # Sentinel 流量控制配置
    sentinel:
      transport:
        dashboard: localhost:8858
        port: 8719
      eager: true
      datasource:
        flow-rules:
          nacos:
            server-addr: localhost:8848
            data-id: sentinel-user-service-flow-rules
            group-id: DEFAULT_GROUP
            rule-type: flow
            data-type: json
        degrade-rules:
          nacos:
            server-addr: localhost:8848
            data-id: sentinel-user-service-degrade-rules
            group-id: DEFAULT_GROUP
            rule-type: degrade
            data-type: json

# 业务配置
cex:
  user:
    # JWT 配置
    jwt:
      secret: your-jwt-secret-key-at-least-32-bytes-long-for-security
      expiration: 86400000  # 24小时过期时间
      refresh-expiration: 604800000  # 7天刷新token过期时间
      issuer: PPCEX
      audience: PPCEX-USER

    # 密码安全配置
    password:
      min-length: 8
      max-length: 20
      require-uppercase: true
      require-lowercase: true
      require-digits: true
      require-special-chars: true
      salt-length: 16
      hash-iterations: 10

    # 登录安全配置
    login:
      max-failed-attempts: 5
      lock-duration: 30  # 账户锁定时间（分钟）
      session-timeout: 1800  # 会话超时时间（秒）
      remember-me-duration: 604800  # 记住我功能持续时间（秒）

    # 注册配置
    register:
      enabled: true
      require-email-verification: true
      require-phone-verification: true
      username-min-length: 3
      username-max-length: 20
      email-whitelist: []
      phone-whitelist: []

    # KYC 配置
    kyc:
      enabled: true
      audit-timeout: 24  # 审核超时时间（小时）
      max-retry-count: 3  # 最大重试提交次数
      supported-countries: ["CN", "US", "UK", "JP", "KR", "SG"]
      id-types: [1, 2, 3]  # 1:身份证, 2:护照, 3:驾驶证

    # 谷歌验证器配置
    google-auth:
      enabled: true
      issuer: PPCEX
      window-size: 3
      code-digits: 6
      qr-code-size: 200

    # 邮箱验证配置
    email-verification:
      enabled: true
      expire-minutes: 30
      max-attempts: 3
      template-code: USER_EMAIL_VERIFY

    # 手机验证配置
    phone-verification:
      enabled: true
      expire-minutes: 10
      max-attempts: 3
      template-code: USER_PHONE_VERIFY

    # 用户资产配置
    asset:
      supported-currencies: ["BTC", "ETH", "USDT", "USD", "CNY"]
      crypto-currencies: ["BTC", "ETH", "USDT"]
      fiat-currencies: ["USD", "CNY"]
      min-withdraw-amount:
        BTC: 0.001
        ETH: 0.01
        USDT: 1.0
        USD: 10.0
        CNY: 50.0

    # 邀请配置
    invite:
      enabled: true
      code-length: 8
      reward-amount: 0  # 邀请奖励金额
      reward-currency: "USDT"
      max-invite-count: 1000

# 安全配置
security:
  # 允许匿名访问的路径
  permit-all:
    - /user/api/v1/auth/**
    - /user/api/v1/public/**
    - /user/doc.html
    - /user/swagger-ui/**
    - /user/v3/api-docs/**
    - /user/actuator/**
    - /user/favicon.ico
    - /user/error

  # 跨域配置
  cors:
    allowed-origins: ["*"]
    allowed-methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    allowed-headers: ["*"]
    exposed-headers: ["Authorization", "Content-Disposition"]
    allow-credentials: true
    max-age: 3600

  # 请求限流配置
  rate-limit:
    enabled: true
    global-limit: 1000  # 全局限流（请求/分钟）
    api-limits:
      "/user/api/v1/auth/register": 5  # 注册接口限流
      "/user/api/v1/auth/login": 10    # 登录接口限流
      "/user/api/v1/user/info": 100    # 用户信息接口限流

# 监控配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,env,beans
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
    metrics:
      enabled: true
      export:
        prometheus:
          enabled: true
    info:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
      profile: ${spring.profiles.active}
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5, 0.95, 0.99
    web:
      server:
        request:
          autotime:
            enabled: true

# 日志配置
logging:
  level:
    root: INFO
    com.ppcex.user: INFO
    com.ppcex.common: INFO
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.cloud: WARN
    com.alibaba.nacos.client: WARN
    io.lettuce.core: WARN
    com.zaxxer.hikari: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] [%X{traceId}] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] [%X{traceId}] %-5level %logger{36} - %msg%n"
  file:
    name: logs/user-service.log
    max-size: 100MB
    max-history: 30
    total-size-cap: 1GB
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 30
      total-size-cap: 1GB
      clean-history-on-start: false

# 线程池配置
thread-pool:
  core:
    core-size: 10
    max-size: 50
    queue-capacity: 1000
    keep-alive-seconds: 60
    thread-name-prefix: user-service-core-
  async:
    core-size: 5
    max-size: 20
    queue-capacity: 500
    keep-alive-seconds: 60
    thread-name-prefix: user-service-async-

# 缓存配置
cache:
  # 本地缓存配置
  local:
    enabled: true
    maximum-size: 1000
    expire-after-write: 300  # 5分钟
    expire-after-access: 600  # 10分钟

  # Redis缓存配置
  redis:
    enabled: true
    default-expiration: 3600  # 1小时
    key-prefix: "user:"
    use-key-prefix: true
    cache-null-values: false
    time-to-live: 3600000

  # 缓存名称配置
  caches:
    user-info:
      ttl: 1800  # 30分钟
      maximum-size: 1000
    user-asset:
      ttl: 300   # 5分钟
      maximum-size: 5000
    kyc-info:
      ttl: 3600  # 1小时
      maximum-size: 1000
    login-token:
      ttl: 86400  # 24小时
      maximum-size: 10000

# 环境特定配置注释
# =================================================================
# 不同环境需要覆盖的配置示例：
#
# 开发环境 (common-config-dev.yaml):
# - spring.cloud.sentinel.transport.dashboard: dev-sentinel:8858
# - logging.level.com.ppcex.user: DEBUG
#
# 测试环境 (common-config-test.yaml):
# - spring.cloud.sentinel.transport.dashboard: test-sentinel:8858
# - logging.level.com.ppcex.user: INFO
#
# 生产环境 (common-config-prod.yaml):
# - spring.cloud.sentinel.transport.dashboard: prod-sentinel-cluster:8858
# - logging.level.com.ppcex.user: WARN
# - cex.user.jwt.secret: 通过环境变量注入
# =================================================================