# =================================================================
# MySQL 数据库配置 - MySQL Database Configuration
# 服务名称: user-service
# 配置组: user-service
# 适用于: 所有环境的MySQL配置
# =================================================================

# 数据源配置
spring:
  datasource:
    # 基础连接配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ppcex_user?useSSL=false&serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&allowPublicKeyRetrieval=true&autoReconnect=true&failOverReadOnly=false&maxReconnects=3
    username: root
    password: root123
    # HikariCP 连接池配置
    hikari:
      # 基础配置
      pool-name: UserServiceHikariCP
      connection-timeout: 30000        # 连接超时时间（毫秒）
      validation-timeout: 5000        # 验证超时时间（毫秒）
      idle-timeout: 600000             # 空闲连接超时时间（毫秒）
      max-lifetime: 1800000            # 连接最大生命周期（毫秒）
      leak-detection-threshold: 60000 # 连接泄漏检测阈值（毫秒）

      # 连接池大小配置
      minimum-idle: 10                 # 最小空闲连接数
      maximum-pool-size: 50            # 最大连接池大小

      # 连接测试配置
      connection-test-query: SELECT 1
      connection-init-sql: SET NAMES utf8mb4

      # 性能优化配置
      register-mbeans: true
      allow-pool-suspension: false
      read-only: false
      isolate-internal-queries: false

  # JPA/Hibernate 配置
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none                   # DDL模式：none, validate, update, create, create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl

    # SQL 输出配置
    show-sql: false
    format-sql: true
    use-sql-comments: false

    # 性能配置
    properties:
      hibernate:
        # 批处理配置
        jdbc:
          batch_size: 25
          order_inserts: true
          order_updates: true
          batch_versioned_data: true

        # 查询缓存配置
        cache:
          use_second_level_cache: false
          use_query_cache: false
          region:
            factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory

        # 统计配置
        generate_statistics: false

        # 连接池配置
        c3p0:
          min_size: 5
          max_size: 20
          timeout: 300
          max_statements: 50
          idle_test_period: 3000

        # 其他配置
        check_nullability: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        use_sql_comments: false
        show_sql: false

  # MyBatis Plus 配置
  mybatis-plus:
    # 基础配置
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.ppcex.user.entity
    type-handlers-package: com.ppcex.user.handler

    # 配置项
    configuration:
      map-underscore-to-camel-case: true    # 下划线转驼峰
      cache-enabled: true                   # 启用缓存
      lazy-loading-enabled: true            # 延迟加载
      multiple-result-sets-enabled: true     # 多结果集
      use-column-label: true                # 使用列标签
      use-generated-keys: false             # 使用生成键
      auto-mapping-behavior: partial        # 自动映射行为
      default-statement-timeout: 25000     # 默认语句超时
      call-setters-on-nulls: false          # 空值调用setter
      return-instance-for-empty-row: false # 空行返回实例

      # 日志配置
      log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

      # 执行器类型
      default-executor-type: reuse

      # 本地缓存配置
      local-cache-scope: statement

    # 全局配置
    global-config:
      db-config:
        id-type: auto                      # ID生成策略
        table-underline: true              # 表名下划线
        logic-delete-field: deleted        # 逻辑删除字段
        logic-delete-value: 1              # 逻辑删除值
        logic-not-delete-value: 0          # 逻辑未删除值
        table-prefix: ""                   # 表名前缀
        capital-mode: false                # 是否大写命名
        db-type: mysql                     # 数据库类型

      # 配置项
      banner: false                        # 是否打印banner
      enable-sql-runner: false             # 是否启用sql runner
      meta-object-handler: com.ppcex.user.config.MyMetaObjectHandler

    # 枚举包
    type-enums-package: com.ppcex.user.enums

    # SQL 注入器
    sql-injector: com.ppcex.user.config.MySqlInjector

    # 分页插件
    pagination:
      enabled: true
      overflow: false
      count: true
      limit: 500

# Flyway 数据库版本控制配置
flyway:
  enabled: true
  locations: classpath:db/migration
  baseline-on-migrate: true
  validate-on-migrate: true
  clean-disabled: true
  table: flyway_schema_history
  sql-migration-separator: "__"
  sql-migration-prefix: "V"
  sql-migration-suffixes: ".sql"
  encoding: UTF-8
  placeholder-replacement: true
  placeholders:
    db_name: ppcex_user
    db_user: root

# 数据库监控配置
datasource-monitor:
  enabled: true
  interval: 60  # 监控间隔（秒）
  metrics:
    - active_connections
    - idle_connections
    - total_connections
    - threads_connections
    - max_used_connections
    - connection_errors_max_connections
    - connection_errors_select
    - connection_errors_timeout
    - slow_queries
    - questions
    - uptime

# 数据库健康检查
datasource-health:
  enabled: true
  timeout: 3000
  check-query: SELECT 1
  expected-result: 1

# 读写分离配置
readwrite-splitting:
  enabled: false
  master-data-source-name: master
  slave-data-source-names: slave1,slave2
  load-balance-algorithm: round_robin
  slave-load-balance-enabled: true

# 分库分表配置
sharding:
  enabled: false
  tables:
    user_info:
      actual-data-nodes: ds$->{0..1}.user_info_$->{0..3}
      table-strategy:
        standard:
          sharding-column: id
          precise-algorithm-class-name: com.ppcex.user.sharding.UserInfoPreciseShardingAlgorithm
          range-algorithm-class-name: com.ppcex.user.sharding.UserInfoRangeShardingAlgorithm
      key-generator:
        column: id
        type: SNOWFLAKE
        props:
          worker-id: 1

  # 数据源配置
  data-sources:
    ds0:
      url: jdbc:mysql://localhost:3306/ppcex_user_0?...
      username: root
      password: root
    ds1:
      url: jdbc:mysql://localhost:3306/ppcex_user_1?...
      username: root
      password: root

# 数据库加密配置
datasource-encryption:
  enabled: false
  algorithm: AES
  key-length: 256
  secret-key: ${DB_ENCRYPTION_KEY:your-encryption-key}
  encrypted-fields:
    - password_hash
    - salt
    - google_auth_secret

# 数据库审计配置
audit:
  enabled: true
  table-name: audit_log
  include:
    - user_info
    - user_kyc
    - user_asset
    - user_login_log
  exclude-fields:
    - create_time
    - update_time
    - deleted

# 环境特定配置注释
# =================================================================
# 不同环境需要覆盖的配置示例：
#
# 开发环境 (mysql-config-dev.yaml):
# - spring.datasource.url: jdbc:mysql://dev-mysql:3306/ppcex_user_dev?...
# - spring.datasource.username: dev_user
# - spring.datasource.password: dev_password
# - spring.jpa.hibernate.ddl-auto: update
#
# 测试环境 (mysql-config-test.yaml):
# - spring.datasource.url: jdbc:mysql://test-mysql:3306/ppcex_user_test?...
# - spring.datasource.username: test_user
# - spring.datasource.password: test_password
# - spring.jpa.hibernate.ddl-auto: validate
#
# 生产环境 (mysql-config-prod.yaml):
# - spring.datasource.url: jdbc:mysql://prod-mysql-cluster:3306/ppcex_user?...
# - spring.datasource.username: ${DB_USERNAME}
# - spring.datasource.password: ${DB_PASSWORD}
# - spring.datasource.hikari.maximum-pool-size: 100
# - readwrite-splitting.enabled: true
# =================================================================