# =================================================================
# Redis Configuration
# Service: user-service
# Group: user-service
# Environment: All
# =================================================================

spring:
  data:
    redis:
      # Connection configuration
      host: localhost
      port: 6379
      password: "root123"
      database: 0
      username: "root"

      # Connection pool configuration
      lettuce:
        pool:
          max-active: 200
          max-wait: -1ms
          max-idle: 10
          min-idle: 0
          time-between-eviction-runs: 30000ms

      # Timeout configuration
      timeout: 10000ms
      connect-timeout: 10000ms
      read-timeout: 10000ms

      # Client name
      client-name: user-service-redis-client

      # Serialization configuration
      serialization:
        key-serializer: org.springframework.data.redis.serializer.StringRedisSerializer
        value-serializer: org.springframework.data.redis.serializer.GenericJackson2JsonRedisSerializer

  # Spring Cache configuration
  cache:
    type: redis
    redis:
      time-to-live: 3600000
      cache-null-values: false
      key-prefix: "user:"
      use-key-prefix: true

# Business cache configuration
cache:
  config:
    # User info cache
    user-info:
      ttl: 1800
      max-size: 1000
      key-prefix: "user:info:"

    # User asset cache
    user-asset:
      ttl: 300
      max-size: 5000
      key-prefix: "user:asset:"

    # KYC info cache
    kyc-info:
      ttl: 3600
      max-size: 1000
      key-prefix: "user:kyc:"

    # Login token cache
    login-token:
      ttl: 86400
      max-size: 10000
      key-prefix: "user:token:"

    # Verification code cache
    verification-code:
      ttl: 300
      max-size: 5000
      key-prefix: "user:code:"

    # User permissions cache
    user-permissions:
      ttl: 1800
      max-size: 1000
      key-prefix: "user:perm:"

# Redis health check configuration
management:
  health:
    redis:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics,redis