# =================================================================
# RocketMQ 消息队列配置 - RocketMQ Message Queue Configuration
# 服务名称: trade-service
# 配置组: trade-service
# 适用于: 所有环境的RocketMQ配置
# =================================================================

# RocketMQ 基础配置
rocketmq:
  # NameServer 地址
  name-server: localhost:9876

  # 生产者配置
  producer:
    # 基础配置
    group: trade-producer-group
    send-message-timeout: 3000           # 发送消息超时时间（毫秒）
    retry-times-when-send-failed: 3      # 同步发送失败重试次数
    retry-times-when-send-async-failed: 3 # 异步发送失败重试次数
    max-message-size: 4194304            # 消息最大大小（4MB）
    compress-message-body-threshold: 4096 # 消息压缩阈值（4KB）

    # 高级配置
    retry-next-server: false             # 失败是否重试下一个broker
    access-key: ""                       # 访问密钥
    secret-key: ""                       # 密钥
    use-tracing: true                    # 启用链路追踪
    namespace: ""                        # 命名空间
    instance-name: trade-service-producer # 实例名称

    # 消息队列选择器
    message-queue-selector: org.apache.rocketmq.client.producer.selector.SelectMessageQueueByHash

    # 消息追踪配置
    enable-msg-trace: true               # 启用消息追踪
    customized-trace-topic: RMQ_SYS_TRACE_TOPIC # 自定义追踪主题

    # 消息发送钩子
    send-message-hooks:
      - com.ppcex.trade.hook.TradeMessageSendHook

    # 事务消息配置
    transaction:
      listener: com.ppcex.trade.listener.TradeTransactionListener
      check-immunity-time: 3000         # 事务消息回查间隔（毫秒）
      check-interval: 60000             # 事务消息回查时间间隔（毫秒）
      transaction-timeout: 60000        # 事务消息超时时间（毫秒）

  # 消费者配置
  consumer:
    # 基础配置
    pull-batch-size: 32                  # 批量拉取消息数量
    consume-thread-min: 20               # 最小消费线程数
    consume-thread-max: 64               # 最大消费线程数
    consume-timeout: 15                  # 消费超时时间（分钟）
    max-reconsume-times: 3               # 最大重试消费次数
    suspend-current-pull-time-millis: 1000 # 挂起当前拉取时间（毫秒）
    consume-message-batch-max-size: 1    # 批量消费消息最大数量

    # 高级配置
    access-key: ""                       # 访问密钥
    secret-key: ""                       # 密钥
    use-tracing: true                    # 启用链路追踪
    namespace: ""                        # 命名空间
    instance-name: trade-service-consumer # 实例名称

    # 消息顺序配置
    orderly: false                       # 是否顺序消费
    consume-orderly: false               # 是否顺序消费（已废弃，使用orderly）

    # 消息队列分配策略
    allocate-message-queue-strategy: org.apache.rocketmq.client.consumer.rebalance.AllocateMessageQueueAveragely

    # 消息过滤配置
    filter:
      use-expression: true              # 是否使用表达式过滤
      expression-type: SQL92             # 过滤表达式类型

    # 消息拉取配置
    pull:
      interval: 1000                     # 拉取间隔（毫秒）
      threshold-for-queue-activity: 1000 # 队列活动阈值

    # 消息消费钩子
    consume-message-hooks:
      - com.ppcex.trade.hook.TradeMessageConsumeHook

    # 消息重试配置
    retry:
      delay-level: 1s 5s 10s 30s 1m 2m 3m 4m 5m 6m 7m 8m 9m 10m 20m 30m 1h 2h
      max-retry-times: 3
      back-off-policy: EXPONENTIAL

    # 消息轨迹配置
    enable-msg-trace: true               # 启用消息轨迹
    customized-trace-topic: RMQ_SYS_TRACE_TOPIC # 自定义轨迹主题

# 消息主题配置
rocketmq-topics:
  # 交易相关主题
  trade:
    topic: trade-topic
    tags:
      - ORDER_CREATE
      - ORDER_CANCEL
      - ORDER_UPDATE
      - ORDER_MATCH
      - ORDER_PARTIAL_MATCH
      - ORDER_FILLED
      - ORDER_EXPIRED
      - ORDER_REJECTED
      - TRADE_EXECUTE
      - POSITION_UPDATE
      - BALANCE_UPDATE
    keys:
      - order_id
      - user_id
      - symbol
      - price
      - amount
      - status

  # 市场数据主题
  market:
    topic: market-topic
    tags:
      - TICKER_UPDATE
      - DEPTH_UPDATE
      - TRADE_UPDATE
      - KLINE_UPDATE
      - MARKET_OPEN
      - MARKET_CLOSE
      - MARKET_PAUSE
      - MARKET_RESUME
    keys:
      - symbol
      - timestamp
      - price
      - volume
      - type

  # 风控主题
  risk:
    topic: risk-topic
    tags:
      - RISK_ALERT
      - POSITION_LIMIT
      - PRICE_DEVIATION
      - VOLUME_SPIKE
      - ACCOUNT_FREEZE
      - ACCOUNT_UNFREEZE
    keys:
      - user_id
      - risk_type
      - severity
      - timestamp

  # 系统主题
  system:
    topic: system-topic
    tags:
      - SYSTEM_STARTUP
      - SYSTEM_SHUTDOWN
      - MAINTENANCE_START
      - MAINTENANCE_END
      - CONFIG_UPDATE
      - ERROR_NOTIFICATION
    keys:
      - system_id
      - event_type
      - timestamp
      - level

# 消息消费者配置
rocketmq-consumers:
  # 交易消息消费者
  trade-consumer:
    group: trade-consumer-group
    topic: trade-topic
    selector-expression: "*"
    consume-mode: CONCURRENTLY          # 消费模式：CONCURRENTLY, ORDERLY
    message-model: CLUSTERING           # 消息模型：CLUSTERING, BROADCASTING
    subscription: trade-subscription
    listener-class: com.ppcex.trade.listener.TradeMessageListener

  # 市场数据消费者
  market-consumer:
    group: market-consumer-group
    topic: market-topic
    selector-expression: "*"
    consume-mode: CONCURRENTLY
    message-model: CLUSTERING
    subscription: market-subscription
    listener-class: com.ppcex.trade.listener.MarketMessageListener

  # 风控消息消费者
  risk-consumer:
    group: risk-consumer-group
    topic: risk-topic
    selector-expression: "*"
    consume-mode: CONCURRENTLY
    message-model: CLUSTERING
    subscription: risk-subscription
    listener-class: com.ppcex.trade.listener.RiskMessageListener

  # 系统消息消费者
  system-consumer:
    group: system-consumer-group
    topic: system-topic
    selector-expression: "*"
    consume-mode: CONCURRENTLY
    message-model: CLUSTERING
    subscription: system-subscription
    listener-class: com.ppcex.trade.listener.SystemMessageListener

# 事务消息配置
rocketmq-transaction:
  enabled: true
  listener-class: com.ppcex.trade.listener.TradeTransactionListener
  check-immunity-time: 3000
  check-interval: 60000
  transaction-timeout: 60000

  # 事务主题配置
  topics:
    order-transaction:
      topic: order-transaction-topic
      producer-group: order-transaction-producer-group
      consumer-group: order-transaction-consumer-group
      listener-class: com.ppcex.trade.listener.OrderTransactionListener

    trade-transaction:
      topic: trade-transaction-topic
      producer-group: trade-transaction-producer-group
      consumer-group: trade-transaction-consumer-group
      listener-class: com.ppcex.trade.listener.TradeTransactionListener

# 消息追踪配置
rocketmq-trace:
  enabled: true
  topic: RMQ_SYS_TRACE_TOPIC
  producer-group: TRADE_TRACE_PRODUCER
  consumer-group: TRADE_TRACE_CONSUMER
  trace-bean-name: tradeTraceBean
  dispatcher-type: MEMORY
  resolve-ip: true
  enable-multi-instance: false

# 消息监控配置
rocketmq-monitor:
  enabled: true
  interval: 60  # 监控间隔（秒）
  metrics:
    - CONSUME_SUCCESS_MSG_COUNT
    - CONSUME_FAILED_MSG_COUNT
    - SEND_SUCCESS_MSG_COUNT
    - SEND_FAILED_MSG_COUNT
    - RT
    - CONSUME_RT
    - PULL_RT
    - PULL_MSG_SIZE
    - SEND_MSG_SIZE
    - CONSUME_MSG_SIZE
    - GROUP_GET_NUMS
    - GROUP_GET_LATENCY
    - TOPIC_PUT_NUMS
    - TOPIC_PUT_SIZE
    - GROUP_GET_LATENCY_BY_STORE

# 消息健康检查
rocketmq-health:
  enabled: true
  timeout: 3000
  check-topic: TRADE_HEALTH_CHECK_TOPIC
  check-group: TRADE_HEALTH_CHECK_GROUP
  check-message: "TRADE_HEALTH_CHECK"

# 延迟消息配置
rocketmq-delay:
  enabled: true
  level: 1s 5s 10s 30s 1m 2m 3m 4m 5m 6m 7m 8m 9m 10m 20m 30m 1h 2h
  topic: TRADE_DELAY_TOPIC
  max-delay-time: 7200000  # 最大延迟时间（2小时）

# 消息幂等性配置
rocketmq-idempotent:
  enabled: true
  key-generator: com.ppcex.trade.idempotent.TradeMessageKeyGenerator
  storage: redis
  redis-key-prefix: "trade:msg:idempotent:"
  expire-time: 86400  # 24小时

# 消息重试配置
rocketmq-retry:
  enabled: true
  max-retry-times: 3
  retry-interval: 1000  # 重试间隔（毫秒）
  retry-policy: EXPONENTIAL  # 重试策略：FIXED, EXPONENTIAL
  backoff-multiplier: 2  # 指数退避倍数

# 消息死信队列配置
rocketmq-dlq:
  enabled: true
  topic: "%DLQ%"  # 死信队列主题前缀
  handle-policy: DISCARD  # 处理策略：DISCARD, DEAD_LETTER, RETRY
  max-retry-times: 3
  retry-interval: 1000

# 顺序消息配置
rocketmq-ordered:
  enabled: true
  topics:
    - trade-topic
    - market-topic
  partition-selector: com.ppcex.trade.selector.TradePartitionSelector
  max-retry-times: 3

# 批量消息配置
rocketmq-batch:
  enabled: true
  max-size: 1024 * 1024  # 1MB
  max-count: 100
  timeout: 1000  # 批量超时时间（毫秒）

# 消息压缩配置
rocketmq-compression:
  enabled: true
  threshold: 4096  # 压缩阈值（4KB）
  type: ZSTD  # 压缩类型：ZSTD, GZIP, LZ4

# 环境特定配置注释
# =================================================================
# 不同环境需要覆盖的配置示例：
#
# 开发环境 (rocketmq-config-dev.yaml):
# - rocketmq.name-server: dev-rocketmq-nameserver:9876
# - rocketmq.producer.group: trade-producer-group-dev
#
# 测试环境 (rocketmq-config-test.yaml):
# - rocketmq.name-server: test-rocketmq-nameserver:9876
# - rocketmq.producer.group: trade-producer-group-test
#
# 生产环境 (rocketmq-config-prod.yaml):
# - rocketmq.name-server: prod-rocketmq-cluster:9876
# - rocketmq.producer.access-key: ${ROCKETMQ_ACCESS_KEY}
# - rocketmq.producer.secret-key: ${ROCKETMQ_SECRET_KEY}
# - rocketmq-topics.trade.topic: trade-topic-prod
# =================================================================

# 消息模板配置示例
rocketmq-message-templates:
  order-create:
    topic: trade-topic
    tag: ORDER_CREATE
    keys: ["order_id", "user_id", "symbol", "price", "amount"]
    delay-time: 0
    retry-times: 3

  order-match:
    topic: trade-topic
    tag: ORDER_MATCH
    keys: ["order_id", "match_id", "price", "amount", "timestamp"]
    delay-time: 0
    retry-times: 3

  trade-execute:
    topic: trade-topic
    tag: TRADE_EXECUTE
    keys: ["trade_id", "order_id", "price", "amount", "timestamp"]
    delay-time: 0
    retry-times: 3

  ticker-update:
    topic: market-topic
    tag: TICKER_UPDATE
    keys: ["symbol", "price", "volume", "timestamp"]
    delay-time: 0
    retry-times: 3