# =================================================================
# 通用配置 - Common Configuration (Nacos版本)
# 服务名称: trade-service
# 配置组: trade-service
# 适用于: 所有环境的基础配置
# =================================================================

# 基础应用配置
spring:
  application:
    name: trade-service

  # Spring Cloud 配置
  cloud:
    # Sentinel 流量控制配置
    sentinel:
      transport:
        dashboard: sentinel:8080
        port: 8719
      eager: true
      datasource:
        flow-rules:
          nacos:
            server-addr: nacos:8848
            dataId: sentinel-trade-service-flow-rules.json
            rule-type: flow
            data-type: json
        degrade-rules:
          nacos:
            server-addr: nacos:8848
            dataId: sentinel-trade-service-degrade-rules.json
            rule-type: degrade
            data-type: json

# 业务配置
cex:
  # JWT 配置
  jwt:
    enabled: true
    secret: your-jwt-secret-key-at-least-32-bytes-long-for-security
    expiration: 86400000  # 24小时过期时间
    refresh-expiration: 604800000  # 7天刷新token过期时间
    issuer: PPCEX
  trade:
    # 交易配置
    trading:
      # 订单配置
      order:
        max-open-orders: 1000  # 单用户最大开仓订单数
        min-order-amount: 0.001  # 最小订单金额
        max-order-amount: 1000000  # 最大订单金额
        price-precision: 8  # 价格精度
        amount-precision: 8  # 数量精度
        fee-rate: 0.001  # 手续费率
        maker-fee-rate: 0.0008  # 挂单手续费率
        taker-fee-rate: 0.0012  # 吃单手续费率

      # 撮合引擎配置
      matching:
        enabled: true
        batch-size: 100  # 批量处理数量
        batch-interval: 100  # 批量处理间隔（毫秒）
        price-tolerance: 0.00000001  # 价格容忍度

      # 风控配置
      risk:
        max-position-size: 1000000  # 最大持仓量
        max-daily-volume: 10000000  # 最大日交易量
        price-deviation-threshold: 0.1  # 价格偏差阈值（10%）
        volatility-threshold: 0.2  # 波动率阈值

    # 交易对配置
    pairs:
      enabled: true
      default-pairs:
        - symbol: "BTC/USDT"
          base-currency: "BTC"
          quote-currency: "USDT"
          min-price: 0.01
          max-price: 1000000
          min-amount: 0.00000001
          max-amount: 10000
          price-precision: 2
          amount-precision: 8
          status: "ACTIVE"
        - symbol: "ETH/USDT"
          base-currency: "ETH"
          quote-currency: "USDT"
          min-price: 0.01
          max-price: 10000
          min-amount: 0.00000001
          max-amount: 10000
          price-precision: 2
          amount-precision: 8
          status: "ACTIVE"

# 安全配置
security:
  # 允许匿名访问的路径
  permit-all:
    - /trade/api/v1/public/**
    - /trade/doc.html
    - /trade/swagger-ui/**
    - /trade/v3/api-docs/**
    - /trade/actuator/**
    - /trade/favicon.ico
    - /trade/error

  # 跨域配置
  cors:
    allowed-origins: ["*"]
    allowed-methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    allowed-headers: ["*"]
    exposed-headers: ["Authorization", "Content-Disposition"]
    allow-credentials: true
    max-age: 3600

  # 请求限流配置
  rate-limit:
    enabled: true
    global-limit: 2000  # 全局限流（请求/分钟）
    api-limits:
      "/trade/api/v1/order/create": 50   # 创建订单接口限流
      "/trade/api/v1/order/cancel": 100  # 取消订单接口限流
      "/trade/api/v1/market/ticker": 1000  # 行情接口限流
      "/trade/api/v1/market/depth": 500   # 深度接口限流

# 监控配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,env,beans
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
    metrics:
      enabled: true
      export:
        prometheus:
          enabled: true
    info:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
      profile: ${spring.profiles.active}
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5, 0.95, 0.99
    web:
      server:
        request:
          autotime:
            enabled: true

# 日志配置
logging:
  level:
    root: INFO
    com.ppcex.trade: INFO
    com.ppcex.common: INFO
    org.springframework.web: DEBUG
    org.springframework.cloud: WARN
    com.alibaba.nacos.client: WARN
    io.lettuce.core: WARN
    com.zaxxer.hikari: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] [%X{traceId}] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] [%X{traceId}] %-5level %logger{36} - %msg%n"
  file:
    name: logs/trade-service.log
    max-size: 100MB
    max-history: 30
    total-size-cap: 1GB
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 30
      total-size-cap: 1GB
      clean-history-on-start: false

# 线程池配置
thread-pool:
  core:
    core-size: 20
    max-size: 100
    queue-capacity: 2000
    keep-alive-seconds: 60
    thread-name-prefix: trade-service-core-
  async:
    core-size: 10
    max-size: 50
    queue-capacity: 1000
    keep-alive-seconds: 60
    thread-name-prefix: trade-service-async-
  matching:
    core-size: 5
    max-size: 20
    queue-capacity: 500
    keep-alive-seconds: 60
    thread-name-prefix: trade-service-matching-

# 缓存配置
cache:
  # 本地缓存配置
  local:
    enabled: true
    maximum-size: 5000
    expire-after-write: 300  # 5分钟
    expire-after-access: 600  # 10分钟

  # Redis缓存配置
  redis:
    enabled: true
    default-expiration: 3600  # 1小时
    key-prefix: "trade:"
    use-key-prefix: true
    cache-null-values: false
    time-to-live: 3600000

  # 缓存名称配置
  caches:
    market-data:
      ttl: 60    # 1分钟
      maximum-size: 10000
    order-book:
      ttl: 30    # 30秒
      maximum-size: 5000
    trade-history:
      ttl: 300   # 5分钟
      maximum-size: 10000
    user-orders:
      ttl: 300   # 5分钟
      maximum-size: 1000
    ticker-data:
      ttl: 60    # 1分钟
      maximum-size: 1000

# 环境特定配置注释
# =================================================================
# 不同环境需要覆盖的配置示例：
#
# 开发环境 (common-config-dev.yaml):
# - spring.cloud.sentinel.transport.dashboard: dev-sentinel:8858
# - logging.level.com.ppcex.trade: DEBUG
#
# 测试环境 (common-config-test.yaml):
# - spring.cloud.sentinel.transport.dashboard: test-sentinel:8858
# - logging.level.com.ppcex.trade: INFO
#
# 生产环境 (common-config-prod.yaml):
# - spring.cloud.sentinel.transport.dashboard: prod-sentinel-cluster:8858
# - logging.level.com.ppcex.trade: WARN
# - cex.trade.trading.order.fee-rate: 通过环境变量注入
# =================================================================