# =================================================================
# MySQL数据库配置 - Database Configuration (Nacos版本)
# 服务名称: risk-service
# 配置组: risk-service
# 适用于: 数据库连接和MyBatis配置
# =================================================================

# 数据源配置
spring:
  datasource:
    # 主数据库配置
    master:
      url: jdbc:mysql://localhost:3306/risk_db?useSSL=false&characterEncoding=utf8&serverTimezone=UTC&allowPublicKeyRetrieval=true
      username: root
      password: password
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource
      hikari:
        # 连接池配置
        pool-name: risk-master-pool
        maximum-pool-size: 20
        minimum-idle: 5
        connection-timeout: 30000
        idle-timeout: 600000
        max-lifetime: 1800000
        leak-detection-threshold: 60000
        validation-timeout: 5000

        # 性能优化
        connection-init-sql: "SET NAMES utf8mb4"
        connection-test-query: "SELECT 1"
        auto-commit: false
        read-only: false

        # 监控配置
        register-mbeans: true

    # 从数据库配置（读写分离）
    slave:
      url: jdbc:mysql://localhost:3307/risk_db?useSSL=false&characterEncoding=utf8&serverTimezone=UTC&allowPublicKeyRetrieval=true
      username: root
      password: password
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource
      hikari:
        # 连接池配置
        pool-name: risk-slave-pool
        maximum-pool-size: 30
        minimum-idle: 10
        connection-timeout: 30000
        idle-timeout: 600000
        max-lifetime: 1800000
        leak-detection-threshold: 60000
        validation-timeout: 5000

        # 性能优化
        connection-init-sql: "SET NAMES utf8mb4"
        connection-test-query: "SELECT 1"
        auto-commit: false
        read-only: true

        # 监控配置
        register-mbeans: true

# MyBatis Plus 配置
mybatis-plus:
  # 基础配置
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.ppcex.risk.entity
  configuration:
    # SQL执行日志配置
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

    # 缓存配置
    cache-enabled: true
    local-cache-scope: session
    default-statement-timeout: 30

    # 数据库映射配置
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    return-instance-for-empty-row: true

    # 性能优化
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
    multiple-result-sets-enabled: true
    use-column-label: true
    use-generated-keys: false
    auto-mapping-behavior: partial

  # 全局配置
  global-config:
    # 数据库配置
    db-config:
      # 主键类型
      id-type: assign_id
      # 表名前缀
      table-prefix: ""
      # 是否使用下划线命名
      table-underline: true
      # 逻辑删除配置
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      # 字段策略
      insert-strategy: not_null
      update-strategy: not_null
      select-strategy: not_null

    # banner配置
    banner: false

  # 注册类型别名
  type-handlers-package: com.ppcex.risk.handler

# 分页插件配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

# 事务配置
spring:
  transaction:
    # 事务管理器配置
    rollback-on-commit-failure: true
    default-timeout: 30

# 数据库监控配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      db:
        enabled: true
      probes:
        enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5, 0.95, 0.99

# 数据库连接池监控
hikari:
  monitoring:
    enabled: true
    interval: 30
    log-level: INFO

# 环境特定配置注释
# =================================================================
# 不同环境需要覆盖的配置示例：
#
# 开发环境 (mysql-config-dev.yaml):
# - spring.datasource.master.url: jdbc:mysql://dev-mysql:3306/risk_db?...
# - spring.datasource.master.username: ${MYSQL_USERNAME}
# - spring.datasource.master.password: ${MYSQL_PASSWORD}
# - mybatis-plus.configuration.log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#
# 测试环境 (mysql-config-test.yaml):
# - spring.datasource.master.url: jdbc:mysql://test-mysql:3306/risk_db?...
# - spring.datasource.master.username: ${MYSQL_USERNAME}
# - spring.datasource.master.password: ${MYSQL_PASSWORD}
# - spring.datasource.master.hikari.maximum-pool-size: 15
#
# 生产环境 (mysql-config-prod.yaml):
# - spring.datasource.master.url: jdbc:mysql://prod-mysql-cluster:3306/risk_db?...
# - spring.datasource.master.username: ${MYSQL_USERNAME}
# - spring.datasource.master.password: ${MYSQL_PASSWORD}
# - spring.datasource.master.hikari.maximum-pool-size: 50
# - spring.datasource.master.hikari.minimum-idle: 20
# =================================================================