# =================================================================
# Redis Configuration
# Service: match-service
# Group: match-service
# Environment: All
# =================================================================

spring:
  data:
    redis:
      # Connection configuration
      host: localhost
      port: 6379
      password: "redis123456"
      database: 0
      username: "cex_user"

      # Connection pool configuration
      lettuce:
        pool:
          max-active: 200
          max-wait: -1ms
          max-idle: 10
          min-idle: 0
          time-between-eviction-runs: 30000ms

      # Timeout configuration
      timeout: 10000ms
      connect-timeout: 10000ms
      read-timeout: 10000ms

      # Client name
      client-name: match-service-redis-client

      # Serialization configuration
      serialization:
        key-serializer: org.springframework.data.redis.serializer.StringRedisSerializer
        value-serializer: org.springframework.data.redis.serializer.GenericJackson2JsonRedisSerializer

  # Spring Cache configuration
  cache:
    type: redis
    redis:
      time-to-live: 3600000
      cache-null-values: false
      key-prefix: "match:"
      use-key-prefix: true

# Business cache configuration
cache:
  config:
    # Order book cache
    order-book:
      ttl: 300
      max-size: 1000
      key-prefix: "match:order:book:"

    # Market data cache
    market-data:
      ttl: 300
      max-size: 5000
      key-prefix: "match:market:"

    # Trade records cache
    trade-records:
      ttl: 86400
      max-size: 10000
      key-prefix: "match:trade:"

    # User orders cache
    user-orders:
      ttl: 1800
      max-size: 5000
      key-prefix: "match:user:order:"

    # Symbol info cache
    symbol-info:
      ttl: 3600
      max-size: 1000
      key-prefix: "match:symbol:"

    # Market statistics cache
    market-stats:
      ttl: 600
      max-size: 1000
      key-prefix: "match:stats:"

# Redis health check configuration
management:
  health:
    redis:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics,redis