# RocketMQ 配置
spring:
  cloud:
    stream:
      rocketmq:
        binder:
          name-server: rocketmq:9876
          group: match-service-group
          access-key:
          secret-key:
          enable-msg-trace: true
          customized-tracker-topic: rmq_sys_trace_topic
      bindings:
        order-input:
          destination: order-topic
          group: match-service-group
          consumer:
            max-attempts: 3
            back-off-initial-interval: 1000
            back-off-multiplier: 2
            back-off-max-interval: 10000
            delay-level-when-next-consume: 0
            subscription: order-topic
            pull-timeout-millis: 30000
            consume-timeout: 15000
            message-model: clustering
            consume-orderly: false
        trade-output:
          destination: trade-topic
          group: match-service-group
          producer:
            group: match-service-producer-group
            send-message-timeout: 3000
            compress-message-body-threshold: 4096
            retry-times-when-send-failed: 2
            retry-next-server: true
            max-message-size: 4194304
        orderbook-output:
          destination: orderbook-topic
          group: match-service-group
          producer:
            group: match-service-producer-group
            send-message-timeout: 3000
            compress-message-body-threshold: 4096
            retry-times-when-send-failed: 2
            retry-next-server: true
            max-message-size: 4194304

# 自定义RocketMQ配置
rocketmq:
  producer:
    group: match-service-producer-group
    send-message-timeout: 3000
    compress-message-body-threshold: 4096
    retry-times-when-send-failed: 2
    retry-next-server: true
    max-message-size: 4194304
  consumer:
    group: match-service-group
    consume-thread-min: 20
    consume-thread-max: 64
    pull-batch-size: 32