spring:
  application:
    name: risk-service
  profiles:
    active: test
  main:
    allow-bean-definition-overriding: true
    lazy-initialization: false
    banner-mode: "off"

  config:
    import:
      - optional:nacos:risk-common-config.yaml
      - optional:nacos:risk-mysql-config.yaml
      - optional:nacos:risk-redis-config.yaml
      - optional:nacos:risk-rocketmq-config.yaml

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        metadata:
          version: 1.0.0
          context-path: /risk
      config:
        enabled: true
        server-addr: localhost:8848
        file-extension: yaml
    stream:
      function:
        definition: riskTopic;userTopic;tradeTopic;assetTopic
      rocketmq:
        binder:
          name-server: localhost:9876

server:
  port: 8008
  servlet:
    context-path: /risk

# Knife4j Configuration
knife4j:
  enable: true
  setting:
    language: zh_cn
    enableSwaggerModels: true
    enableDocumentManage: true
    swaggerModelName: 实体类列表
    enableVersion: false
    enableReloadCacheParameter: false
    enableFilterMultipartApis: false
    enableFilterMultipartMethods: false
    enableRequestCache: true
    enableHost: false
    enableHomeCustom: true
    homeCustomLocation: classpath:markdown/home.md
    enableAfterScript: true
    enableSwaggerAuth: true
  enableRequestCache: true
  enableHost: false
  openapi:
    title: PPCEX Risk Service API
    description: 风控服务API文档
    email: support@ppcex.com
    concat: PPCEX Team
    url: https://www.ppcex.com
    version: v1.0.0
    license: MIT License
    license-url: https://opensource.org/licenses/MIT

debug: false