# =================================================================
# 通用配置 - Common Configuration (Nacos版本)
# 服务名称: market-service
# 配置组: market-service
# 适用于: 所有环境的基础配置
# =================================================================

# 基础应用配置
spring:
  application:
    name: market-service

  # Spring Cloud 配置
  cloud:
    # Sentinel 流量控制配置
    sentinel:
      transport:
        dashboard: sentinel:8080
        port: 8719
      eager: true
      datasource:
        flow-rules:
          nacos:
            server-addr: nacos:8848
            dataId: sentinel-market-service-flow-rules.json
            rule-type: flow
            data-type: json
        degrade-rules:
          nacos:
            server-addr: nacos:8848
            dataId: sentinel-market-service-degrade-rules.json
            rule-type: degrade
            data-type: json

# 业务配置
cex:
  # JWT 配置
  jwt:
    enabled: true
    secret: your-jwt-secret-key-at-least-32-bytes-long-for-security
    expiration: 86400000  # 24小时过期时间
    refresh-expiration: 604800000  # 7天刷新token过期时间
    issuer: PPCEX

  # 市场服务配置
  market:
    # 数据同步配置
    sync:
      # 交易对同步配置
      pairs:
        enabled: true
        sync-interval: 300  # 同步间隔（秒）
        retry-interval: 60  # 重试间隔（秒）
        max-retry: 3  # 最大重试次数

      # 行情数据同步配置
      ticker:
        enabled: true
        update-interval: 1000  # 更新间隔（毫秒）
        batch-size: 100  # 批量处理大小
        cache-ttl: 60  # 缓存TTL（秒）

      # K线数据同步配置
      kline:
        enabled: true
        intervals: ["1m", "5m", "15m", "30m", "1h", "4h", "1d", "1w", "1M"]
        history-limit: 1000  # 历史数据限制
        generate-interval: 60000  # 生成间隔（毫秒）

      # 深度数据同步配置
      depth:
        enabled: true
        update-interval: 500  # 更新间隔（毫秒）
        depth-limit: 20  # 深度限制
        snapshot-interval: 5000  # 快照间隔（毫秒）

      # 成交数据同步配置
      trade:
        enabled: true
        update-interval: 2000  # 更新间隔（毫秒）
        history-limit: 1000  # 历史数据限制
        cleanup-interval: 3600000  # 清理间隔（毫秒）

    # WebSocket 配置
    websocket:
      enabled: true
      max-sessions: 10000  # 最大连接数
      session-timeout: 300000  # 会话超时（毫秒）
      message-size-limit: 65536  # 消息大小限制
      heartbeat-interval: 30000  # 心跳间隔（毫秒）

    # 数据聚合配置
    aggregation:
      enabled: true
      # 24小时统计重置时间（UTC时间）
      daily-reset-time: "00:00:00"
      # 统计计算间隔
      calculation-interval: 60000  # 1分钟
      # 数据保留时间
      data-retention:
        ticker: 30  # 行情数据保留30天
        kline: 90  # K线数据保留90天
        trade: 7  # 成交数据保留7天
        depth: 1  # 深度数据保留1天

    # 缓存配置
    cache:
      # 本地缓存配置
      local:
        enabled: true
        maximum-size: 10000
        expire-after-write: 300  # 5分钟
        expire-after-access: 600  # 10分钟

      # Redis缓存配置
      redis:
        enabled: true
        default-expiration: 3600  # 1小时
        key-prefix: "market:"
        use-key-prefix: true
        cache-null-values: false
        time-to-live: 3600000

      # 缓存名称配置
      caches:
        market-pairs:
          ttl: 3600  # 1小时
          maximum-size: 100
        ticker-data:
          ttl: 60  # 1分钟
          maximum-size: 1000
        kline-data:
          ttl: 300  # 5分钟
          maximum-size: 50000
        trade-data:
          ttl: 120  # 2分钟
          maximum-size: 10000
        depth-data:
          ttl: 30  # 30秒
          maximum-size: 1000

# 安全配置
security:
  # 允许匿名访问的路径
  permit-all:
    - /market/api/v1/public/**
    - /market/doc.html
    - /market/swagger-ui/**
    - /market/v3/api-docs/**
    - /market/actuator/**
    - /market/favicon.ico
    - /market/error

  # 跨域配置
  cors:
    allowed-origins: ["*"]
    allowed-methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    allowed-headers: ["*"]
    exposed-headers: ["Authorization", "Content-Disposition"]
    allow-credentials: true
    max-age: 3600

  # 请求限流配置
  rate-limit:
    enabled: true
    global-limit: 5000  # 全局限流（请求/分钟）
    api-limits:
      "/market/api/v1/market/ticker/*": 1000  # 行情接口限流
      "/market/api/v1/market/klines": 2000   # K线接口限流

# 监控配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,env,beans
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
    metrics:
      enabled: true
      export:
        prometheus:
          enabled: true
    info:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
      profile: ${spring.profiles.active}
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5, 0.95, 0.99
    web:
      server:
        request:
          autotime:
            enabled: true
      "/market/api/v1/market/trades": 1000   # 成交接口限流
      "/market/api/v1/market/depth": 2000   # 深度接口限流
      "/market/api/v1/pairs": 500           # 交易对接口限流

# 监控配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,env,beans
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
    metrics:
      enabled: true
      export:
        prometheus:
          enabled: true
    info:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
      profile: ${spring.profiles.active}
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5, 0.95, 0.99
    web:
      server:
        request:
          autotime:
            enabled: true

# 日志配置
logging:
  level:
    root: INFO
    com.ppcex.market: INFO
    com.ppcex.common: INFO
    org.springframework.web: DEBUG
    org.springframework.cloud: WARN
    com.alibaba.nacos.client: WARN
    io.lettuce.core: WARN
    com.zaxxer.hikari: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] [%X{traceId}] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] [%X{traceId}] %-5level %logger{36} - %msg%n"
  file:
    name: logs/market-service.log
    max-size: 100MB
    max-history: 30
    total-size-cap: 1GB
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 30
      total-size-cap: 1GB
      clean-history-on-start: false

# 线程池配置
thread-pool:
  core:
    core-size: 20
    max-size: 100
    queue-capacity: 2000
    keep-alive-seconds: 60
    thread-name-prefix: market-service-core-
  async:
    core-size: 15
    max-size: 50
    queue-capacity: 1000
    keep-alive-seconds: 60
    thread-name-prefix: market-service-async-
  websocket:
    core-size: 10
    max-size: 50
    queue-capacity: 1000
    keep-alive-seconds: 60
    thread-name-prefix: market-service-websocket-

# 环境特定配置注释
# =================================================================
# 不同环境需要覆盖的配置示例：
#
# 开发环境 (common-config-dev.yaml):
# - spring.cloud.sentinel.transport.dashboard: dev-sentinel:8858
# - logging.level.com.ppcex.market: DEBUG
# - cex.market.sync.pairs.sync-interval: 60
#
# 测试环境 (common-config-test.yaml):
# - spring.cloud.sentinel.transport.dashboard: test-sentinel:8858
# - logging.level.com.ppcex.market: INFO
# - cex.market.sync.pairs.sync-interval: 300
#
# 生产环境 (common-config-prod.yaml):
# - spring.cloud.sentinel.transport.dashboard: prod-sentinel-cluster:8858
# - logging.level.com.ppcex.market: WARN
# - cex.market.websocket.max-sessions: 50000
# - security.rate-limit.global-limit: 10000
# =================================================================