# =================================================================
# Redis配置 - Redis Configuration (Nacos版本)
# 服务名称: market-service
# 配置组: market-service
# 适用于: Redis连接和缓存配置
# =================================================================

spring:
  redis:
    # Redis连接配置
    host: localhost
    port: 6379
    password:
    database: 1  # 市场服务使用数据库1
    timeout: 10000  # 连接超时时间（毫秒）
    ssl: false
    lettuce:
      pool:
        max-active: 100  # 最大连接数
        max-idle: 20    # 最大空闲连接数
        min-idle: 5     # 最小空闲连接数
        max-wait: 3000  # 获取连接最大等待时间（毫秒）
        time-between-eviction-runs: 30000  # 空闲连接检测间隔（毫秒）
        min-evictable-idle-time: 60000     # 空闲连接最小存活时间（毫秒）
        test-on-borrow: false
        test-on-return: false
        test-while-idle: true

# 缓存配置
cache:
  # 本地缓存配置 (Caffeine)
  local:
    enabled: true
    maximum-size: 10000  # 最大缓存条目数
    expire-after-write: 300  # 写入后过期时间（秒）
    expire-after-access: 600  # 访问后过期时间（秒）
    refresh-after-write: 60  # 写入后刷新时间（秒）
    initial-capacity: 100  # 初始容量
    record-stats: true  # 是否记录统计信息

  # Redis缓存配置
  redis:
    enabled: true
    key-prefix: "market:"
    use-key-prefix: true
    cache-null-values: false
    default-expiration: 3600  # 默认过期时间（秒）
    time-to-live: 3600000  # TTL（毫秒）
    cache-configuration:
      market-pairs: 3600    # 交易对缓存1小时
      ticker-data: 60       # 行情数据缓存1分钟
      kline-data: 300       # K线数据缓存5分钟
      trade-data: 120       # 成交数据缓存2分钟
      depth-data: 30        # 深度数据缓存30秒
      market-statistics: 300  # 市场统计缓存5分钟
      rate-limit: 300       # 限流缓存5分钟

# 特定缓存配置
market:
  cache:
    # 行情数据缓存
    ticker:
      enabled: true
      ttl: 60  # 1分钟
      maximum-size: 1000
      refresh-interval: 10  # 10秒刷新一次

    # K线数据缓存
    kline:
      enabled: true
      ttl: 300  # 5分钟
      maximum-size: 50000
      preload-intervals: ["1m", "5m", "15m", "1h", "1d"]  # 预加载的时间间隔

    # 成交数据缓存
    trade:
      enabled: true
      ttl: 120  # 2分钟
      maximum-size: 10000
      recent-trades-limit: 1000  # 最近成交记录数量限制

    # 深度数据缓存
    depth:
      enabled: true
      ttl: 30  # 30秒
      maximum-size: 1000
      snapshot-interval: 5  # 快照间隔（秒）

    # 市场统计缓存
    statistics:
      enabled: true
      ttl: 300  # 5分钟
      calculation-interval: 60  # 计算间隔（秒）

# Redis发布订阅配置
redis:
  pubsub:
    enabled: true
    channels:
      market-updates: "market:updates"      # 市场更新频道
      ticker-updates: "ticker:updates"       # 行情更新频道
      trade-updates: "trade:updates"        # 成交更新频道
      depth-updates: "depth:updates"        # 深度更新频道
      system-commands: "system:commands"     # 系统命令频道

# Redis集群配置（生产环境使用）
# spring:
#   redis:
#     cluster:
#       nodes:
#         - redis-node1:6379
#         - redis-node2:6379
#         - redis-node3:6379
#       max-redirects: 3
#     timeout: 10000
#     password: your-redis-password

# Redis哨兵配置（高可用环境使用）
# spring:
#   redis:
#     sentinel:
#       master: mymaster
#       nodes:
#         - sentinel1:26379
#         - sentinel2:26379
#         - sentinel3:26379
#       password: your-sentinel-password

# 环境特定配置注释
# =================================================================
# 开发环境 (redis-config-dev.yaml):
# - spring.redis.database: 1
# - spring.redis.lettuce.pool.max-active: 50
# - cache.local.maximum-size: 5000
#
# 测试环境 (redis-config-test.yaml):
# - spring.redis.database: 2
# - spring.redis.password: test-redis-password
# - spring.redis.lettuce.pool.max-active: 100
#
# 生产环境 (redis-config-prod.yaml):
# - spring.redis.password: prod-redis-password
# - spring.redis.lettuce.pool.max-active: 200
# - spring.redis.ssl: true
# - cache.local.maximum-size: 20000
# =================================================================