# Notify Service Common Configuration
spring:
  main:
    allow-bean-definition-overriding: true
    lazy-initialization: false
    banner-mode: "off"

# MyBatis Plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

# 邮件配置
spring:
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:your-email@gmail.com}
    password: ${MAIL_PASSWORD:your-app-password}
    protocol: smtp
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.ssl.trust: ${MAIL_HOST:smtp.gmail.com}

# Knife4j Configuration
knife4j:
  enable: true
  openapi:
    title: 通知服务API文档
    description: 通知服务接口文档
    email: dev@ppcex.com
    concat: PPCEX Team
    url: https://www.ppcex.com
    version: v1.0.0
    license: Apache 2.0
    license-url: http://www.apache.org/licenses/LICENSE-2.0.html
  setting:
    language: zh_cn
    enable-swagger-models: true
    swagger-model-name: 实体类列表